thisshellhas(): add permission check on cap scripts
bin/modernish:
- No longer rely on '.' to handle permission errors on cap/*.t
  scripts. Instead, before dotting it, check if we have read
  permission for it, and return a fatal error status 2 if not.
  This triggers proper fatal error handling with die().
- Do --show in thisshellhas() itself instead of _Msh_cacheCap().
- Some mild refactoring.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -628,13 +628,13 @@ _Msh_doUse() {
 # ___ thisshellhas ____________________________________________________________
 # Test if all of the given words are shell keywords, regular or special
 # built in commands, shell options, or (for words that are in all caps)
-# optional capabilities or bugs that modernish found in the current shell.
+# capbilities (features, quirks, bugs or warnings) detected for this shell.
 #
 # Usage: thisshellhas <item> [ <item> ... ]
 #        thisshellhas [ --cache | --show ]
 #
 # If <item> contains only uppercase letter, digits or '_', return the result
-# of the associated modernish feature, quirk or bug test.
+# of the associated modernish capability test.
 # If <item> is an all-lowercase word, check if it's a shell reserved word or
 # built-in command on the current shell.
 # If <item> starts with --rw= or --kw=, check if it's a shell reserved word.
@@ -643,10 +643,10 @@ _Msh_doUse() {
 # long-form shell option by that name.
 # If <item> is any other letter or digit preceded by a single '-', check if
 # this shell has a short-form shell option by that character.
-# --cache: run all external bug/quirk/feature tests and cache the results
+# --cache: run all capability detection tests and cache the results
 # --show: like --cache, but also output all the IDs of positive results, one per line
 #
-# Feature/quirk/bug tests and shell option checks are cached in a variable
+# Capability detection tests and shell option checks are cached in a variable
 # so repeated checks are not inefficient.
 unset -v _Msh_cap	# unexport, just in case
 _Msh_cap=''
@@ -658,27 +658,18 @@ _Msh_cap=''
 _Msh_doCapTest() {
 	unset -v _Msh_test						# guarantee unset variable for testing purposes
 	set -- "$MSH_PREFIX/lib/modernish/cap/$1.t"			# this can be used by test scripts as well
-	PATH=$DEFPATH command test -f "$1"
-	case $? in
-	( 0 )	. "$1" 1>&2 ;;
-	( 1 )	return 127 ;;
-	( * )	die "thisshellhas: doCapTest: 'test' failed" || return ;;
-	esac
+	PATH=$DEFPATH command test -f "$1" || return			# return 1 if not found, > 1 (fatal) if 'test' fails
+	PATH=$DEFPATH command test -r "$1" || return 2
+	. "$1" 1>&2
 }
-# Pre-cache the results of all the external capability/bug tests.
+# Pre-cache the results of all the capability/bug tests.
 _Msh_cacheCap() {
 	case ${_Msh_cap} in
 	( '#ALLCACHED '* )
-		if str eq "${1-}" '--show'; then
-			push IFS -f
-			IFS=' '; set -f
-			putln ${_Msh_cap#?ALLCACHED}
-			pop IFS -f
-		fi
 		return ;;	# already done
 	esac
-	push IFS -f _Msh_c _Msh_newCap
-	# do any external tests that haven't already been done
+	push IFS -f _Msh_c
+	# do any tests that haven't already been done
 	IFS=''; set +f
 	for _Msh_c in "$MSH_PREFIX"/lib/modernish/cap/*.t; do
 		_Msh_c=${_Msh_c##*/}
@@ -689,17 +680,16 @@ _Msh_cacheCap() {
 		thisshellhas "${_Msh_c}"
 	done
 	# eliminate negative test results; they are redundant with #ALLCACHED tag
-	_Msh_newCap=''
+	set --
 	IFS=' '; set -f
 	for _Msh_c in ${_Msh_cap}; do
 		case ${_Msh_c} in
 		( !* ) continue ;;
 		esac
-		_Msh_newCap=${_Msh_newCap:+${_Msh_newCap} }${_Msh_c}
+		set -- "$@" "${_Msh_c}"
 	done
-	str eq "${1-}" '--show' && putln ${_Msh_newCap}
-	_Msh_cap="#ALLCACHED ${_Msh_newCap}"
-	pop IFS -f _Msh_c _Msh_newCap
+	_Msh_cap="#ALLCACHED $*"
+	pop IFS -f _Msh_c
 }
 
 # ** Shell-specific code for thisshellhas():
@@ -864,13 +854,17 @@ eval 'thisshellhas() {
 	( 0,* )	die "thisshellhas: need at least 1 argument, got $#" || return ;;
 	( *a* )	set +a; thisshellhas "$@"; eval "set -a; return $?" ;;
 	esac
-	while :; do
+	while case $# in (0) break;; esac; do
 		case $1 in
 		( --cache )
 			_Msh_cacheCap
 			;;
 		( --show )
-			_Msh_cacheCap --show
+			_Msh_cacheCap
+			push IFS -f
+			IFS=" "; set -f
+			putln ${_Msh_cap#?ALLCACHED}
+			pop IFS -f
 			;;
 		( "" | --bi= | --[rk]w= | --bi=*/* | --[rk]w=*/* \
 		| --bi=*[!\[\]\!{}"$SHELLSAFECHARS"]* \
@@ -938,8 +932,7 @@ eval 'thisshellhas() {
 				case $? in
 				( 0 )	_Msh_cap=${_Msh_cap:+${_Msh_cap} }$1
 					unset -v _Msh_test ;;
-				( 1 | 127 )	# 127 = *.t file not found
-					_Msh_cap=${_Msh_cap:+${_Msh_cap} }!$1
+				( 1 )	_Msh_cap=${_Msh_cap:+${_Msh_cap} }!$1
 					unset -v _Msh_test
 					return 1 ;;
 				( * )	die "thisshellhas(): failure while testing for $1" || return ;;
@@ -948,9 +941,6 @@ eval 'thisshellhas() {
 			;;
 		esac
 		shift
-		case $# in
-		( 0 )	break ;;
-		esac
 	done
 }'"${CCn}" || _Msh_initExit "thisshellhas() definition: 'eval' failed"
 unset -v _Msh_tSH_testBI _Msh_tSH_testKW _Msh_tSH_bashLEPIPEMAIN
@@ -2673,7 +2663,8 @@ _Msh_doIsOnSameFs() {
 _Msh_doCapTest() {
 	unset -v _Msh_test						# guarantee unset variable for testing purposes
 	set -- "$MSH_PREFIX/lib/modernish/cap/$1.t"			# this can be used by test scripts as well
-	is -L reg "$1" || return 127
+	is -L reg "$1" || return 1
+	can read "$1" || return 2
 	. "$1" 1>&2
 }
 
