do all of modernish initialisation with PATH=/dev/null
bin/modernish:
- Instead of repeatedly disabling $PATH where needed, do the entire
  initialisation of modernish with PATH=/dev/null. This securely
  keeps external commands from interfering with feature tests. Only
  minor adaptations were needed to make this work on all shells
  (including yash -o posix which checks $PATH for the external
  equivalent of regular builtins before accessing the builtin).
- Move some code to more logical places: _Msh_initExit() is moved
  forward; IFS is saved in the same place as PATH; all cleanup is
  now done at the end of stage 2 init.
- On shells without 'typeset', avoid forking a subshell for the
  KSH88FUNC/KSH93FUNC feature test.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -76,8 +76,49 @@ MSH_VERSION=0.9.1dev
 MSH_SHELL=${MSH_SHELL:-$(PATH=$DEFPATH sh -c 'command -v sh || which sh || echo /bin/sh')}
 MSH_PREFIX=${srcdir:-$PWD}		# this line and the previous will be changed by install.sh
 
-# Save $PATH for tests that need to change it.
+# Internal function for aborting initialisation.
+# Usage: _Msh_initExit "error message"
+_Msh_initExit() {
+	PATH=$DEFPATH
+	if [ -e ~/.modernish-force ]; then
+		printf 'modernish: %s\n' "$@" "Continuing anyway. THINGS WILL BREAK." 1>&2
+		PATH=/dev/null
+		return 0
+	fi
+	printf 'modernish: %s\n' "$@" "Initialisation failed. Aborting." 1>&2
+	MSH_VERSION=failedinit
+	readonly MSH_VERSION
+	case $- in
+	( *i* )	# try not to exit an interactive shell
+		PATH=${_Msh_PATH}
+		case ${_Msh_IFS+s} in
+		( s )	IFS=${_Msh_IFS} ;;
+		( * )	unset -v IFS ;;
+		esac
+		kill -INT "$$" || kill -s INT "$$" ;;
+	esac 2>|/dev/null
+	\exit 124
+}
+
+# Do the entire initialisation with PATH=/dev/null, so we can test for builtins without external commands interfering.
+# Don't use regular builtins (e.g. 'test'/'[') without PATH=$DEFPATH, or yash in POSIX mode won't find them.
 _Msh_PATH=$PATH
+PATH=/dev/null
+
+# Save IFS (including its value and whether it is set or unset) to restore it at the end of initialisation.
+# Due to BUG_IFSISSET on ksh93, we can't test if IFS is set by any normal method, and we also can't know yet if we're on ksh93
+# or not. So use the workaround here, which is to analyse field splitting behaviour (this thankfully works on all shells).
+_Msh_testFn() {
+	case ${IFS:+n} in	# non-empty: it is set
+	( '' )	set -- "a b c"	# empty: test for default field splitting
+		set -- $1
+		case $# in
+		( 1 )	;;	# no field splitting: it is empty and set
+		( * )	! : ;;	# default field splitting: it is unset
+		esac ;;
+	esac
+}
+_Msh_testFn && _Msh_IFS=$IFS || unset -v _Msh_IFS
 
 # Remove all aliases from the execution environment, as some shells set
 # unhelpful default aliases. (Particularly, AT&T ksh sets
@@ -87,7 +128,6 @@ _Msh_PATH=$PATH
 # On interactive shells, only remove certain aliases that would definitely
 # interfere, to avoid undoing system or user profile settings.
 unset -v _Msh_FTL_UNALIASA
-PATH=/dev/null	# thwart external 'unalias' on BSD and Mac OS X
 case $- in
 ( *i* )	\unalias command alias unalias set unset exit return eval die ;;
 ( * )	\unalias -a \
@@ -95,24 +135,6 @@ case $- in
 	( s )	\unalias -m '*' ;;
 	esac || _Msh_FTL_UNALIASA=y ;;
 esac 2>| /dev/null
-PATH=${_Msh_PATH}
-
-# Internal function for aborting initialisation.
-# Usage: _Msh_initExit "error message"
-_Msh_initExit() {
-	PATH=${_Msh_PATH}
-	if [ -e ~/.modernish-force ]; then
-		printf 'modernish: %s\n' "$@" "Continuing anyway. THINGS WILL BREAK." 1>&2
-		return 0
-	fi
-	printf 'modernish: %s\n' "$@" "Initialisation failed. Aborting." 1>&2
-	MSH_VERSION=failedinit
-	readonly MSH_VERSION
-	case $- in
-	( *i* )	kill -INT "$$" || kill -s INT "$$" ;;	# try not to exit an interactive shell
-	esac 2>/dev/null
-	\exit 124
-}
 
 # _Msh_cap (capabilities; also quirks and bugs) is space-separated. Each ID in
 # ${_Msh_cap} should only contain ASCII capital letters A-Z, digits 0-9, and (for
@@ -257,32 +279,6 @@ export POSIXLY_CORRECT=y	# this also sets -o posix on bash
 # NOTE: all tests need to be compatible with all the bugs tested for (even
 # the fatal ones), so that modernish can give a full report.
 
-# Save IFS (including its value and whether it is set or unset) to restore
-# it at the end of the tests.
-# Due to BUG_IFSISSET on ksh93, we can't test if IFS is set by any normal
-# method, and we also can't know yet if we're on ksh93 or not, so use the
-# workaround here, which is to analyse field splitting behaviour (this
-# thankfully works on all shells).
-_Msh_testFn() {
-	case ${IFS:+n} in		# non-empty: it is set
-	( '' )	set -- "a b c"		# empty: test for default field splitting
-		set -- $1
-		case $# in
-		( 1 )	;;		# no field splitting: it is empty and set
-		( 3 )	false ;;	# default field splitting: it is unset
-		( * )	_Msh_initExit "Internal error with field splitting!" ;;
-		esac ;;
-	esac
-}
-_Msh_testFn && _Msh_IFS=$IFS || unset -v _Msh_IFS
-
-# For the next four tests, disable $PATH to avoid finding spurious
-# external versions of 'alias', 'unalias' and 'command' (*BSD, Mac)
-# for shells that don't have these built in.
-# Don't use normal builtins (including 'test' and '[') without PATH set,
-# or yash in POSIX mode won't find them (as POSIX mandates).
-PATH=/dev/null
-
 # FTL_NOALIAS: No aliases (Debian posh; bash "minimal configuration").
 alias test=test 2>|/dev/null || _Msh_have FTL_NOALIAS 'No support for aliases at all.'
 unalias test 2>|/dev/null	# AT&T ksh93 can't unalias in a subshell. Since install.sh does a test
@@ -329,8 +325,6 @@ case " ${_Msh_cap} " in
 ( *\ FTL_NOALIAS\ * ) ;;	# skip: not applicable
 ( * )	command -V type >| /dev/null 2>&1 || alias type='command -V' ;;
 esac
-
-PATH=${_Msh_PATH}
 
 # FTL_DEVCLOBBR: Can't write to devices if 'set -o noclobber' is active.
 # Workaround: use >| instead of >
@@ -556,10 +550,8 @@ fi
 # contains a value that cannot be converted to arithmetic. (yash < 2.40)
 case " ${_Msh_cap} " in
 ( *" FTL_NOARITH "* ) ;;  # Skip: not applicable.
-( * )	PATH=/dev/null
-	unset -v _Msh_test2
+( * )	unset -v _Msh_test2
 	{ command -v typeset && typeset -i _Msh_test2; } >|/dev/null 2>&1  # suppress ksh93 rendering variable as float exponential
-	PATH=${_Msh_PATH}
 	_Msh_test2=$((1000005))
 	_Msh_test=foo\\bar
 	( : "$((_Msh_test = 1000005))" ) 2>|/dev/null && : "$((_Msh_test = 1000005))"
@@ -619,7 +611,7 @@ esac
 # FTL_FNREDIR: I/O redirections on function definition commands are not
 # remembered or honoured when the function is executed. (zsh < 5.0.7)
 _Msh_testFn() {
-	[ -t 0 ]
+	PATH=$DEFPATH test -t 0
 } </dev/tty
 _Msh_testFn <&- || _Msh_have FTL_FNREDIR "I/O redir on function defs ignored.${ZSH_VERSION+ (zsh 5.0.7 fixes this)}"
 
@@ -794,16 +786,15 @@ esac
 
 # LOCAL: Function-local variables using the 'local' or 'typeset' special
 # builtin or shell keyword on functions defined using POSIX syntax().
-if PATH=/dev/null; _Msh_testFn() { local _Msh_test || return; _Msh_test=7; } \
-&& _Msh_test=42 && _Msh_testFn && PATH=${_Msh_PATH} && case ${_Msh_test} in (42);; (*) ! : ;; esac; then
+if _Msh_testFn() { local _Msh_test || return; _Msh_test=7; } \
+&& _Msh_test=42 && _Msh_testFn && case ${_Msh_test} in (42);; (*) ! : ;; esac; then
 	_Msh_have LOCAL
-elif PATH=/dev/null; _Msh_testFn() { typeset _Msh_test || return; _Msh_test=7; } \
-&& _Msh_test=42 && _Msh_testFn && PATH=${_Msh_PATH} && case ${_Msh_test} in (42);; (*) ! : ;; esac; then
+elif _Msh_testFn() { typeset _Msh_test || return; _Msh_test=7; } \
+&& _Msh_test=42 && _Msh_testFn && case ${_Msh_test} in (42);; (*) ! : ;; esac; then
 	# alias it on pdksh/mksh -- and yash, if not in posix mode
 	alias local=typeset
 	_Msh_have LOCAL
 fi 2>|/dev/null
-PATH=${_Msh_PATH}
 
 # KSH88FUNC: define ksh-style shell functions with the 'function' keyword,
 # supporting local variables with the 'typeset' builtin. 
@@ -812,7 +803,7 @@ PATH=${_Msh_PATH}
 # - On AT&T ksh93, local variables are ONLY possible on functions defined
 #   with the 'function' keyword and by using the 'typeset' builtin.
 # This feature test was based on Q28 at http://kornshell.com/doc/faq.html
-if (PATH=/dev/null; eval 'function foo { :; }' && typeset foo=bar); then
+if command -v typeset && (eval 'function foo { :; }' && typeset foo=bar); then
 	eval '
 	function _Msh_testFn {
 		_Msh_test2=${_Msh_test}
@@ -828,7 +819,7 @@ if (PATH=/dev/null; eval 'function foo { :; }' && typeset foo=bar); then
 	( global ) _Msh_have KSH93FUNC ;;
 	( local )  _Msh_have KSH88FUNC ;;
 	esac
-fi 2>|/dev/null
+fi >|/dev/null 2>&1
 
 # --- Control character constants ---
 
@@ -940,9 +931,6 @@ case ${_Msh_ftlcount} in
 ( 1 )	_Msh_initExit "1 fatal shell bug found. This shell can't run modernish." ;;
 ( * )	_Msh_initExit "${_Msh_ftlcount} fatal shell bugs found. This shell can't run modernish." ;;
 esac
-IFS=''	# (Delay restoring IFS to init phase 2.)
-unset -f _Msh_testFn _Msh_testFn2
-unset -v _Msh_test _Msh_test2 _Msh_ftlcount
 
 # -------------
 
@@ -5175,19 +5163,6 @@ mkcd() {
 # successfully, so everything can be used except features based on aliases
 # (such as 'not', 'so').
 
-# Restore IFS.
-case ${_Msh_IFS+s} in
-( s )	IFS=${_Msh_IFS}; unset -v _Msh_IFS ;;
-( * )	unset -v IFS ;;
-esac
-
-# Cleanup.
-unset -v _Msh_PATH _Msh_test
-unset -f _Msh_initExit _Msh_have
-
-# With init succeeded, time to make these permanent.
-#readonly MSH_VERSION MSH_SHELL MSH_PREFIX	# installer will uncomment this
-
 # If shell supports it, then set modernish functions to read-only.
 if thisshellhas ROFUNC; then
 	: @ROFUNC@	# installer tag to replace with 'readonly -f'
@@ -5250,6 +5225,18 @@ _Msh_tmp_doHashbangPreload() {
 	done
 	unset -v _Msh_doHbPl_L _Msh_doHbPl_C _Msh_doHbPl_a
 }
+
+# Cleanup.
+case ${_Msh_IFS+s} in
+( s )	IFS=${_Msh_IFS}; unset -v _Msh_IFS ;;
+( * )	unset -v IFS ;;
+esac
+PATH=${_Msh_PATH}
+unset -v _Msh_PATH _Msh_test _Msh_test2 _Msh_ftlcount
+unset -f _Msh_testFn _Msh_testFn2 _Msh_initExit _Msh_have
+
+# With init succeeded, time to make these permanent.
+#readonly MSH_VERSION MSH_SHELL MSH_PREFIX	# installer will uncomment this
 
 # --------------------
 # ------- MAIN -------
