fixes for busybox ash; FTL_EVALERR
bin/modernish:
* Fixes for busybox ash 1.25.1:
  - Busybox now supports the ksh88 'function' keyword, but does
    not have 'typeset'. This caused a false positive for KSH93FUNC
    in the built-in KSH88FUNC/KSH93FUNC feature test, resulting in
    subsequent breakage. Fixed by checking for the success of
    'typeset' in that feature test.
  - Wrap the '[[' version of can() and is() in an 'eval' to avoid
    causing a grammar parsing error on busybox ash; even tough it
    does not have '[[', it apparently chokes on a '[[' containing
    parentheses.
* Fatal error test for busybox 1.26.0. This version introduces a
  bug where 'eval' does not return a non-success exit status if it
  encounters a syntax error. This kills feature testing based on
  shell-grammatical features, such as causing false positive in
  HERESTR.t plus the resulting subsequent breakage. This version
  of busybox ash cannot run modernish. Introducing a new fatal
  bug test FTL_EVALERR (at the expense of another subshell fork).

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -433,6 +433,12 @@ if ! _Msh_testFn; then
 	_Msh_have FTL_EVALRET "No return from function if 'return' within 'eval'.${YASH_VERSION+ (yash 2.39 fixes this)}"
 fi
 
+# FTL_EVALERR: 'eval' does not return an error exit status (> 0) on syntax
+# error. This kills all feature testing based on shell grammar features,
+# giving false positives on tests like HERESTR.t, causing subsequent breakage.
+# (Found on busybox 1.26.0)
+(eval '(') 2>/dev/null && _Msh_have FTL_EVALERR "No error exit status from 'eval' on syntax error."
+
 # FTL_ROUNDMLN: AT&T ksh version "M 1993-12-28 s+" (pre-installed version
 # on Mac OS X 10.7) has rounding errors in integer arithmetic when ordinary
 # shell assignments or comparisons are used on numbers greater than one
@@ -728,7 +734,7 @@ case $(PATH=/dev/null; eval '
 		_Msh_test2=${_Msh_test}
 	}
 	function _Msh_testFn2 {
-		typeset _Msh_test=local
+		typeset _Msh_test=local || return
 		_Msh_testFn
 	}' &&
 	_Msh_test=global &&
@@ -4028,7 +4034,8 @@ if thisshellhas --rw=[[; then
 	# Use [[ if available because it's generally faster and more robust;
 	# this also avoids BUG_TESTPAREN in zsh 5.0.6/5.0.7 which makes it
 	# impossible for test/[ to check for files named '(', ')' or '!'.
-	can() {
+	# (Wrap in 'eval' to avoid parsing error on shells without '[[')
+	eval 'can() {
 		case $# in
 		( 1 )	case $1 in
 			( read | write | exec | traverse )
@@ -4047,7 +4054,7 @@ if thisshellhas --rw=[[; then
 				[[ -x $2 && -d $2 ]] ;;
 			( * )	die "can: invalid operator: $1" ;;
 			esac ;;
-		( * )	_Msh_dieArgs can "$#" '1 or 2' ;;
+		( * )	_Msh_dieArgs can "$#" "1 or 2" ;;
 		esac
 	}
 	is() {
@@ -4131,9 +4138,9 @@ if thisshellhas --rw=[[; then
 				[[ $2 -ef $3 ]] ;;
 			( * )	die "is: invalid arguments" ;;
 			esac ;;
-		( * )	_Msh_dieArgs is "$#" '1 or 2' ;;
+		( * )	_Msh_dieArgs is "$#" "1 or 2" ;;
 		esac
-	}
+	}'
 else
 	can() {
 		case $# in
