use(): bugfix: don't use 'push'/'pop', as push/pop may call 'use'
bin/modernish:
- use(): Fix bug introduced in 45375da9 that could cause 'push' to
  be in an inconsistent state when using 'push -o'.

lib/_install/bin/modernish.bundle.diff:
- Update.

lib/modernish/mdl/_IN/opt.mm:
- Add reminder comment not to use push/pop in init.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -571,6 +571,12 @@ setstatus() {
 # Option -e: query if the module exists.
 _Msh_using=''
 use() {
+	case $- in
+	( *a* )	# Make sure modules are initialised without allexport.
+		# Note: module init must never 'set -a', or this will break on recursive module init.
+		# (We can't use 'push -a'/'pop -a' here, because 'push'/'pop' may itself call 'use'.)
+		set +a; use "$@"; eval "set -a; return $?" ;;
+	esac
 	unset -v _Msh_use_o
 	while	case ${1-} in
 		( -- )		shift; break ;;
@@ -599,11 +605,9 @@ use() {
 		is reg "$MSH_MDL/$1.mm" || is dir "$MSH_MDL/$1"
 		return ;;
 	esac
-	push --key=_Msh_use -a
-	set +a  # don't export module vars
 	_Msh_using=${_Msh_using}${_Msh_using:+ }$1
 	if is dir "$MSH_MDL/$1" && ! is reg "$MSH_MDL/$1.mm"; then
-		let "$# == 1" || { pop --key=_Msh_use -a; die "use: arguments cannot be passed to module directory: $1"; }
+		let "$# == 1" || die "use: arguments cannot be passed to module directory: $1"
 		# recursively initialise all modules...
 		push -f; set +f; set -- "$MSH_MDL/$1"/*; pop -f
 		for _Msh_use_F do
@@ -616,13 +620,9 @@ use() {
 		unset -v _Msh_use_F
 		return
 	fi
-	is reg "$MSH_MDL/$1.mm" || { pop --key=_Msh_use -a; die "use: module $1 not found"; }
-	_Msh_doUse "$@"
-	pop --key=_Msh_use --keepstatus -a
-	case $? in
-	( 0 )	if isset -i && ! str begin "$1" '_IN/' && ! insubshell; then putln "Using $1"; fi ;;
-	( * )	die "use: initialisation of module $1 failed" ;;
-	esac
+	is reg "$MSH_MDL/$1.mm" || die "use: module $1 not found"
+	_Msh_doUse "$@" || die "use: initialisation of module $1 failed"
+	if isset -i && ! str begin "$1" '_IN/' && ! insubshell; then putln "Using $1"; fi
 } >&2
 # Wrapping the dot command in its own function works around bugs or quirks
 # with 'return' on a couple of shells (yash < 2.44, older FreeBSD sh).
diff --git a/lib/_install/bin/modernish.bundle.diff b/lib/_install/bin/modernish.bundle.diff
--- a/lib/_install/bin/modernish.bundle.diff
+++ b/lib/_install/bin/modernish.bundle.diff
@@ -1,5 +1,5 @@
---- bin/modernish	2020-01-27 23:57:08.000000000 +0100
-+++ bin/modernish.tmp	2020-01-28 02:06:44.000000000 +0100
+--- bin/modernish	2020-01-28 22:57:38.000000000 +0100
++++ /tmp/temp.r%d,DtORJx/patched_bin_modernish	2020-01-28 22:57:39.000000000 +0100
 @@ -30,49 +30,7 @@
  # -------------
  
@@ -185,16 +185,15 @@
  
  # Extended 'exit'. Usage: exit [ -u ] [ <status> [ <message> ] ]
  # The <status> is a shell arithmetic expression.
-@@ -620,7 +496,7 @@
- 	_Msh_doUse "$@"
- 	pop --key=_Msh_use --keepstatus -a
- 	case $? in
--	( 0 )	if isset -i && ! str begin "$1" '_IN/' && ! insubshell; then putln "Using $1"; fi ;;
-+	( 0 )	;;
- 	( * )	die "use: initialisation of module $1 failed" ;;
- 	esac
+@@ -622,7 +498,6 @@
+ 	fi
+ 	is reg "$MSH_MDL/$1.mm" || die "use: module $1 not found"
+ 	_Msh_doUse "$@" || die "use: initialisation of module $1 failed"
+-	if isset -i && ! str begin "$1" '_IN/' && ! insubshell; then putln "Using $1"; fi
  } >&2
-@@ -666,42 +542,12 @@
+ # Wrapping the dot command in its own function works around bugs or quirks
+ # with 'return' on a couple of shells (yash < 2.44, older FreeBSD sh).
+@@ -666,42 +541,12 @@
  # so repeated checks are not inefficient.
  
  # ** First, some internal functions to support thisshellhas():
@@ -241,7 +240,7 @@
  }
  
  # ** Shell-specific code for thisshellhas():
-@@ -897,16 +743,6 @@
+@@ -897,16 +742,6 @@
  	esac
  	while case $# in (0) break;; esac; do
  		case $1 in
@@ -258,7 +257,7 @@
  		( "" | --bi= | --[rk]w= | --bi=*/* | --[rk]w=*/* \
  		| --bi=*[!\[\]\!{}"$SHELLSAFECHARS"]* \
  		| --[rk]w=*[!\[\]\!{}"$SHELLSAFECHARS"]* \
-@@ -955,7 +791,7 @@
+@@ -955,7 +790,7 @@
  		( * )	'"${_Msh_tSH_bashLEPIPEMAIN}"'
  			case " ${_Msh_cap} " in
  			( *" $1 "* )	;;
@@ -267,7 +266,7 @@
  			( * )	_Msh_doCapTest "$1"
  				case $? in
  				( 0 )	_Msh_cap=${_Msh_cap:+${_Msh_cap} }$1
-@@ -2565,16 +2401,6 @@
+@@ -2565,16 +2400,6 @@
  
  # --- End of core library, start of initialisation phase 2 ---
  
@@ -284,7 +283,7 @@
  # If shell supports it, then set modernish functions to read-only.
  if thisshellhas ROFUNC; then
  	readonly -f \
-@@ -2666,22 +2492,12 @@
+@@ -2666,22 +2491,12 @@
  if ! str end "$0" '/modernish' && ! str eq "$0" 'modernish'; then
  
  	# --- modernish was sourced (simple use) ---
@@ -307,7 +306,7 @@
  	unset -f _Msh_tmp_doHashbangPreload
  	# Restore 'allexport' option if it was set
  	if isset _Msh_allexport; then
-@@ -2786,16 +2602,6 @@
+@@ -2786,16 +2601,6 @@
  			}
  			_Msh_tmp_doUse "${1#--use=}"
  			unset -f _Msh_tmp_doUse ;;
@@ -324,7 +323,7 @@
  		( --version | --help )
  			putln "This is modernish version $MSH_VERSION." \
  			      "Not installed. Run install.sh to set up modernish with your preferred shell." \
-@@ -2803,7 +2609,6 @@
+@@ -2803,7 +2608,6 @@
  			      "Known-good shell:	MSH_SHELL=$MSH_SHELL" \
  			      "Default utility PATH:	DEFPATH=$DEFPATH" \
  			      "User config directory:	MSH_CONFIG=$MSH_CONFIG"
