new basic system util: mkcd
bin/modernish:
- Starting a new category of small basic system utilities that
  should have been part of the standard shell, but aren't. Since
  their implementation is inexpensive, they go in the main library.
- Adding mkcd(): make one or more directories, then, upon success,
  change into the last-mentioned one.

README.md:
- Document mkcd().

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -4540,6 +4540,26 @@ unset -f _Msh_tmp_getWorkingTr
 
 # -------------------
 
+# Basic system utilities.
+
+# mkcd: make one or more directories, then cd into the last-mentioned one.
+# All given arguments are passed to mkdir, so usage depends on mkdir.
+if thisshellhas BUG_UPP; then
+	mkcd() {
+		command -p mkdir ${1+"$@"} || die "mkcd: mkdir failed"
+		shift "$(( $# - 1 ))"
+		command -p cd -- "$1" || die "mkcd: cd failed"
+	}
+else
+	mkcd() {
+		command -p mkdir "$@" || die "mkcd: mkdir failed"
+		shift "$(( $# - 1 ))"
+		command -p cd -- "$1" || die "mkcd: cd failed"
+	}
+fi
+
+# -------------------
+
 # Initialization, phase 2.
 
 # At this point, all main modernish library functionality was initialised
