use(): minor bugfix; force subshell fork on ksh93
bin/modernish: use():
- Replace broken method to ensure 'set -a' (-o allexport) isn't
  active during module initialisation. Use the stack.
- On ksh93, if we're loading a module in a subshell, force a fork
  to avoid masses of problems related to non-forking subshells.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -540,21 +540,25 @@ use() {
 		is reg "$MSH_MDL/$1.mm" || is dir "$MSH_MDL/$1"
 		return ;;
 	esac
+	push --key=_Msh_use -a
+	set +a  # don't export module vars
 	_Msh_doUse "$@"
 	case $? in
 	( 0 )	if isset -i && ! str begin "$1" '_IN/'; then putln "Using $1" >&2; fi
 		_Msh_using=${_Msh_using}${_Msh_using:+$CCn}$1 ;;
-	( * )	die "use: initialisation of module $1 failed" ;;
+	( * )	pop --key=_Msh_use -a; die "use: initialisation of module $1 failed" ;;
 	esac
+	pop --key=_Msh_use --keepstatus -a
 }
 _Msh_doUse() {
+	case ${KSH_VERSION-} in
+	( 'Version '* | 2[0-9][0-9][0-9].* )
+		# If a module is initialised in a subshell on ksh93, force it to fork to avoid many bugs.
+		# Ref.: https://github.com/att/ast/issues/480
+		let .sh.subshell && command ulimit -t unlimited 2>/dev/null ;;
+	esac
 	if is reg "$MSH_MDL/$1.mm"; then
-		case $- in
-		( *a* )	set +a
-			. "$MSH_MDL/$1.mm" >&2
-			eval "set -a; return $?" ;;
-		( * )	. "$MSH_MDL/$1.mm" >&2 ;;
-		esac
+		. "$MSH_MDL/$1.mm" >&2
 	elif is dir "$MSH_MDL/$1"; then
 		let "$# == 1" || die "use: arguments cannot be passed to module directory: $1"
 		# recursively initialise all modules...
