Stack trap: save exit status for traps; document minor PPs incompat
bin/modernish:
- Execute stack and POSIX traps with $? initially set to the exit
  status that was active at the time the signal was triggered.

README.md:
- Document this change.
- Point out that neither stack or POSIX traps have access to the
  positional parameters.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1011,6 +1011,8 @@ case $- in
 	esac
 	readonly _Msh_psBroken
 	die() {
+		# Save current exit status for DIE traps.
+		_Msh_E=$?
 		# Try to prevent loops.
 		case ${_Msh_die_isrunning+s} in
 		( s )	_Msh_doExit 125 "$@" ;;
@@ -1025,11 +1027,11 @@ case $- in
 		# (Preserving stdin allows 'stty' to restore terminal state from a trap.)
 		{	case ${_Msh__V_Msh_trapDIE__SP+s} in
 			( s )	while let "(_Msh__V_Msh_trapDIE__SP-=1) >= 0"; do
-					_Msh_doOneStackTrap DIE "${_Msh__V_Msh_trapDIE__SP}" 0<&8 &
+					_Msh_doOneStackTrap DIE "${_Msh__V_Msh_trapDIE__SP}" "${_Msh_E}" 0<&8 &
 				done ;;
 			esac
 			case ${_Msh_POSIXtrapDIE+p} in
-			( p )	_Msh_doPosixTrap DIE 0<&8 & ;;
+			( p )	_Msh_doPosixTrap DIE "${_Msh_E}" 0<&8 & ;;
 			esac
 			put "${ME##*/} died${1+: $@}$CCn" >/dev/tty
 			if ! is onterminal 2; then
@@ -3160,6 +3162,8 @@ poptrap() {
 # the commands, as they may be trapped repeatedly. Also handle the traps for
 # the POSIX 'trap' command defined below.
 _Msh_doTraps() {
+	# Save current exit status in $3.
+	set -- "$1" "$2" "$?"
 	# Execute the commands on the trap stack, last to first, if any.
 	# Deactivate the trap stack if we're in a subshell; bad things happen if a subshell inherits
 	# pushed traps from the main shell, e.g. modules cleaning up after themselves prematurely.
@@ -3168,7 +3172,7 @@ _Msh_doTraps() {
 		while let '(_Msh_doTraps_i-=1) >= 0'; do
 			# Execute each stack trap in a subshell, so 'exit' cannot stop the trap stack and
 			# traps from different modules can't interfere with each other (or the main shell).
-			(_Msh_doOneStackTrap "${2}" "${_Msh_doTraps_i}")
+			(_Msh_doOneStackTrap "${2}" "${_Msh_doTraps_i}" "${3}")
 		done
 		unset -v _Msh_doTraps_i
 	fi
@@ -3177,7 +3181,7 @@ _Msh_doTraps() {
 	# should not use any functionality from modernish modules that push
 	# their own traps to clean up after themselves.
 	if isset "_Msh_POSIXtrap${2}"; then
-		_Msh_doPosixTrap "${2}"
+		_Msh_doPosixTrap "${2}" "${3}"
 	fi
 	# On interactive shells, SIGINT is used for cleanup after die(), so clear
 	# out the SIGINT stack traps to make sure they are executed only once.
@@ -3219,8 +3223,8 @@ _Msh_doTraps() {
 # Another benefit is that we can clear the positional parameters for the trap (with 'shift').
 # (The trick is that the enveloping 'eval' has already expanded ${1} before 'shift' clears it.)
 _Msh_doPosixTrap() {
-	eval "shift; eval \" \${_Msh_POSIXtrap${1}}\""
-		#           ^ QRK_EVALNOOPT compat: can't use '--' so use space for safe arbitrary commands.
+	eval "shift 2; setstatus $2; eval \" \${_Msh_POSIXtrap${1}}\""
+		#			    ^ QRK_EVALNOOPT compat: can't use '--' so use space for safe arbitrary commands.
 		# http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_19_16
 }
 # Same for a stack trap. Always run this in a subshell.
@@ -3240,7 +3244,7 @@ _Msh_doOneStackTrap() {
 		done
 	fi
 	# execute trap
-	eval "shift 2; eval \" \${_Msh__V_Msh_trap${1}__S${2}}\""
+	eval "shift 3; setstatus $3; eval \" \${_Msh__V_Msh_trap${1}__S${2}}\""
 }
 
 # Alias the builtin 'trap' command to a replacement to avoid overwriting other
