str ematch: proper POSIX ERE compatibility on POSIX shells
This introduces a new ERE converter for use by 'str ematch' on
shells that cannot internally parse EREs. aux/ematch.awk quickly
converts POSIX EREs to traditional awk EREs so they can be matched
by any awk published in the last few decades.

lib/_install/goodawk.sh, lib/modernish/cap/WRN_EREBOUNDS.t:
- Removed.

install.sh:
- Remove code dealing with aux/goodawk.sh.

lib/modernish/aux/ematch.awk:
- Added for invocation by 'str ematch'.
- Converts POSIX EREs to traditional awk REs, expanding bounds and
  adapting backslash usage.
- On old awks that do not support POSIX locale features (collating
  symbols, equivalence classes, character classes), this translates
  these to traditional ASCII equivalents, which is better than
  nothing. A system that has such a default awk is unlikely to
  support anything but ASCII anyway.

bin/modernish: str ematch:
- On POSIX shells, use aux/ematch.awk to properly parse POSIX EREs.

lib/modernish/tst/match.t:
- Make the POSIX ERE regression test a bit more challenging, as it
  tests the correctness of aux/ematch.awk on shells that do not
  have a built-in means of handling EREs.

README.md:
- Remove WRN_EREBOUNDS documentation.

share/doc/modernish/CODINGSTYLE:
- Specify that library functions must not assume a modern awk.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -2131,28 +2131,14 @@ _Msh_doMatch='case $3 in
 	esac'
 
 # Determine code for extended regular expression test.
-# Usage: str ematch <string> <extended-regex>
-#
-# Use the [[ keyword (or '[' on yash) if available and if it supports
-# extended regular expressions. This is much faster than the standard method
-# which involves invoking the external grep command.
-#
-# Empty removal handling: if one argument is omitted, assume the first was a
-# removed unquoted empty parameter and return false. 0 arguments = fatal error.
 if thisshellhas DBLBRACKETERE; then
-	# Wrap the function definition in 'eval', otherwise shells that
-	# have '[[' but don't support '=~' fail to parse the script.
 	_Msh_doEMatch='[[ $2 =~ $3 ]]'
 elif thisshellhas --bi=test && PATH=$DEFPATH command test aaa '=~' '^a{2,}$' 2>/dev/null; then
 	# yash and zsh support extended regex matching in builtin test/[
 	_Msh_doEMatch='test "$2" "=~" "$3"'
 else
-	# Default/POSIX: use awk's match().
-	. "$MSH_PREFIX/lib/_install/goodawk.sh" || _Msh_awk='PATH=$DEFPATH command awk' # install.sh will replace this line
-	_Msh_doEMatch="POSIXLY_CORRECT=y _Msh_V=\$2 _Msh_R=\$3 ${_Msh_awk} \\
-			'BEGIN { exit(!match(ENVIRON[\"_Msh_V\"],ENVIRON[\"_Msh_R\"])); }' \\
-		|| { let \"\$? > 1\" && die \"str ematch: 'awk' failed\"; }"
-	unset -v _Msh_awk
+	_Msh_doEMatch='POSIXLY_CORRECT=y PATH=$DEFPATH command awk -f "$MSH_AUX/ematch.awk" "$2" "$3" \
+		|| { let "$? > 1" && die "str ematch: '\''awk'\'' failed"; }'
 fi
 
 # Determine code for lexical comparison.
