0.1: initial redesign of is(), can() [incomplete, not working yet]

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3775,14 +3775,14 @@ fi 2>/dev/null
 
 # --- General file tests. ---
 
-# exists "$file": tests if file exists.
-# exists -L "$file": tests if file exists and is not an invalid symlink.
-# (This is written to cope correctly with a file with the literal name '-L',
-# without the need to add '--', even though -L is also an option.)
+# TODO: re-document in comments
+
 if thisshellhas [[; then
 	# Use [[ if available because it's generally faster and more robust;
 	# this also avoids BUG_TESTPAREN in zsh 5.0.6/5.0.7 which makes it
 	# impossible for test/[ to check for files named '(', ')' or '!'.
+
+	# TODO: 'exists -L' is still not empty removal compatible. Make part of is()?
 	exists() {
 		case ${#},${1-} in
 		( 1,* )		[[ -e $1 || -L $1 ]] ;;
@@ -3790,6 +3790,106 @@ if thisshellhas [[; then
 		( 2,-* )	die "exists: invalid option: $1" || return ;;
 		( 2,* )		die "exists: only one non-option argument allowed" || return ;;
 		( * )		_Msh_dieArgs exists "$#" '1 or 2' || return ;;
+		esac
+	}
+	can() {
+		case $# in
+		( 1 )	case $1 in
+			( read | write | exec | traverse )
+				# removed empty argument: return false
+				return 1 ;;
+			( * )	die "can: invalid operator: $1" ;;
+			esac ;;
+		( 2 )	case $1 in
+			( read )
+				[[ -d $2 && ( -r $2 && -x $2 ) || -r $2 ]] ;;
+			( write )
+				[[ -d $2 && ( -w $2 && -x $2 ) || -w $2 ]] ;;
+			( exec )
+				[[ -x $2 && ! -d $2 ]] ;;
+			( traverse )
+				[[ -x $2 && -d $2 ]] ;;
+			( * )	die "can: invalid operator: $1" ;;
+			esac ;;
+		( * )	_Msh_dieArgs can "$#" '1 or 2' ;;
+		esac
+	}
+	is() {
+		case $# in
+		( 1 )	case $1 in
+			( exist | reg | dir | sym | fifo | socket | blockspecial | charspecial \
+			nonempty | setuid | setgid | mine | mygroup )
+				# removed empty argument: return false
+				return 1 ;;
+			( * )	die "is: invalid operator: $1" ;;
+			esac ;;
+		( 2 )	case $1 in
+			( exist )
+				[[ -e $2 || -L $2 ]] ;;
+			( reg )	[[ ! -L $2 && -f $2 ]] ;;
+			( dir )	[[ ! -L $2 && -d $2 ]] ;;
+			( sym )	[[ -L $2 ]] ;;
+			( fifo )
+				[[ ! -L $2 && -p $2 ]] ;;
+			( socket )
+				[[ ! -L $2 && -S $2 ]] ;;
+			( blockspecial )
+				[[ ! -L $2 && -b $2 ]] ;;
+			( charspecial )
+				[[ ! -L $2 && -c $2 ]] ;;
+			( nonempty )
+				if [[ -d $2 ]]; then
+					[[ -r $2 && -x $2 ]] || return 2
+					case $- in
+					( *f* ) set +f; set -- "$2" "$2"/[*] "$2"/* "$2"/.[!.]* "$2"/.??*; set -f ;;
+					( * )	set -- "$2" "$2"/[*] "$2"/* "$2"/.[!.]* "$2"/.??* ;;
+					esac
+					[[ "${#} $2 $3 $4 $5" != "5 $1/[*] $1/* $1/.[!.]* $1/.??*" ]]
+				else
+					[[ -s $2 ]]
+				fi ;;
+			( setuid )
+				[[ -u $2 ]] ;;
+			( setgid )
+				[[ -g $2 ]] ;;
+			( mine )
+				[[ -O $2 ]] ;;
+			( mygroup )
+				[[ -G $2 ]] ;;
+			( onterminal )
+				case $2 in
+				( *[!0123456789]* )
+					die "is onterminal: invalid file descriptor: $2" ;;
+				( * )	[[ -t $2 ]] ;;
+				esac ;;
+			( -L )	case $2 in
+				( exist | reg | dir | sym | fifo | socket | blockspecial | charspecial )
+					# removed empty argument: return false
+					return 1 ;;
+				( * )	die "is -L: invalid operator: $2" ;;
+				esac ;;
+			( * )	die "is: invalid operator: $2" ;;
+			esac ;;
+		( 3 )	case $1 in
+			( -L )	case $2 in
+				( exist )
+					[[ -e $3 ]] ;;
+				( reg )	[[ -f $3 ]] ;;
+				( dir )	[[ -d $3 ]] ;;
+				( sym )	[[ -L $3 && -e $3 ]] ;;	# "is -L sym": test if valid symlink. TODO: is this logical?
+				( fifo )
+					[[ -p $3 ]] ;;
+				( socket )
+					[[ -S $3 ]] ;;
+				( blockspecial )
+					[[ -b $3 ]] ;;
+				( charspecial )
+					[[ -c $3 ]] ;;
+				( * )	die "is -L: invalid operator: $2" ;;
+				esac ;;
+			( * )	die "is: invalid arguments" ;;
+			esac
+		( * )	_Msh_dieArgs is "$#" '1 or 2' ;;
 		esac
 	}
 else
@@ -3802,203 +3902,110 @@ else
 		( * )		_Msh_dieArgs exists "$#" '1 or 2' || return ;;
 		esac || { let "$? > 1" && die "exists: '[' failed"; }
 	}
-fi
-
-# Test if file exists, is not an invalid symlink, and is non-empty. Unlike
-# 'test -s', this also works for directories in which you have read
-# permission. A race condition with tests like this is inevitable (even
-# with the traditional 'test -s'). Be careful with parallel processing!
-# Exit status:
-# 0: file or directory (after resolving any symlinks) is not empty
-# 1: file or directory is empty, doesn't exist, or is an invalid symlink
-# 2: no read permission in directory, so cannot test if directory is empty
-# The directory testing method was kindly provided by Stéphane Chazelas in:
-# Message-ID: <20150524190928.GB6744@chaz.gmail.com>
-# https://groups.google.com/forum/#!original/comp.unix.shell/M_gDU9uk8Rk/FyiS9m-RFYAJ
-if thisshellhas [[; then
-	# Use [[ if available because it's generally faster and more robust;
-	# this also avoids BUG_TESTPAREN in zsh 5.0.6/5.0.7 which makes it
-	# impossible for test/[ to check for files named '(', ')' or '!'.
-	isnonempty() {
+	can() {
 		case $# in
-		( 1 )	if [[ -d $1 ]]; then
-				[[ -r $1 && -x $1 ]] || return 2
-				case $- in
-				( *f* ) set +f; set -- "$1" "$1"/[*] "$1"/* "$1"/.[!.]* "$1"/.??*; set -f ;;
-				( * )	set -- "$1" "$1"/[*] "$1"/* "$1"/.[!.]* "$1"/.??* ;;
-				esac
-				[[ "${#} $2 $3 $4 $5" != "5 $1/[*] $1/* $1/.[!.]* $1/.??*" ]]
-			else
-				_Msh_fileTest isnonempty s -L "$@"
-			fi ;;
-		( * )	_Msh_dieArgs isnonempty "$#" 1 || return ;;
-		esac
-	}
-else
-	isnonempty() {
-		case $# in
-		( 1 )	if [ -d "$1" ] || { let "$? > 1" && die "isnonempty: '[ -d' failed"; }; then
-				[ -r "$1" ] && [ -x "$1" ] || { let "$? > 1" && die "isnonempty: '[' failed"; } || return 2
-				case $- in
-				( *f* ) set +f; set -- "$1" "$1"/[*] "$1"/* "$1"/.[!.]* "$1"/.??*; set -f ;;
-				( * )	set -- "$1" "$1"/[*] "$1"/* "$1"/.[!.]* "$1"/.??* ;;
-				esac
-				case "${#} $2 $3 $4 $5" in
-				( "5 $1/[*] $1/* $1/.[!.]* $1/.??*" )
-					return 1 ;;
-				esac
-			else
-				_Msh_fileTest isnonempty s -L "$@"
-			fi ;;
-		( * )	_Msh_dieArgs isnonempty "$#" 1 || return ;;
-		esac
-	}
-fi
-
-# --- File permission tests. ---
-# Note: These automatically resolve symlinks.
-
-# Test if this program can read from or write to a file or directory. Work
-# around botched '['/'[[' logic that claims you can (-r)ead from or (-w)rite
-# to a directory even if its "x" bit is not set.
-if thisshellhas [[; then
-	# Use [[ if available because it's generally faster and more robust;
-	# this also avoids BUG_TESTPAREN in zsh 5.0.6/5.0.7 which makes it
-	# impossible for test/[ to check for files named '(', ')' or '!'.
-	canread() {
-		case $# in
-		( 1 )	if	[[ -d $1 ]]
-			then	[[ -r $1 && -x $1 ]]
-			else	[[ -r $1 ]]
-			fi ;;
-		( * )	_Msh_dieArgs "canread" $# 1 ;;
-		esac
-	}
-	canwrite() {
-		case $# in
-		( 1 )	if	[[ -d $1 ]]
-			then	[[ -w $1 && -x $1 ]]
-			else	[[ -w $1 ]]
-			fi ;;
-		( * )	_Msh_dieArgs "canwrite" $# 1 ;;
-		esac
-	}
-else
-	canread() {
-		case $# in
-		( 1 )	if	[ -d "$1" ] || { let "$? > 1" && die "canread: '[ -d' failed"; }
-			then	[ -r "$1" ] && [ -x "$1" ]
-			else	[ -r "$1" ]
-			fi || { let "$? > 1" && die "canread: '[' failed"; } ;;
-		( * )	_Msh_dieArgs "canread" $# 1 ;;
-		esac
-	}
-	canwrite() {
-		case $# in
-		( 1 )	if	[ -d "$1" ] || { let "$? > 1" && die "canwrite: '[ -d' failed"; }
-			then	[ -w "$1" ] && [ -x "$1" ]
-			else	[ -w "$1" ]
-			fi || { let "$? > 1" && die "canwrite: '[' failed"; } ;;
-		( * )	_Msh_dieArgs "canwrite" $# 1 ;;
-		esac
-	}
-fi
-
-# Test if file is executable or directory is pass-throughable.
-alias canexec='_Msh_fileTest canexec x -L'
-
-# Test if file has user or group ID bits set.
-alias issetuid='_Msh_fileTest issetuid u -L'
-alias issetgid='_Msh_fileTest issetgid g -L'
-
-# Test if file is owned by user or by current user's main group.
-# (Note: the -O and -G test/[ operators are technically non-standard, but
-# their support in shells that can run the rest of modernish is universal.)
-alias ismine='_Msh_fileTest ismine O -L'
-alias ismygroup='_Msh_fileTest ismygroup G -L'
-
-# --- File type tests. ---
-
-# Test if file is a symlink.
-alias issym='_Msh_fileTest issym L -L'
-
-# Note: The following tests do *not* resolve symlinks unless the -L option is
-# used. This is to promote security and discourage allowing symlink attacks.
-
-alias isreg='_Msh_fileTest isreg f'
-alias isdir='_Msh_fileTest isdir d'
-alias isfifo='_Msh_fileTest isfifo p'
-alias issocket='_Msh_fileTest issocket S'
-alias isblockspecial='_Msh_fileTest isblockspecial b'
-alias ischarspecial='_Msh_fileTest ischarspecial c'
-
-# Internal function. Not for direct use.
-# (It is written to cope correctly with a file with the literal name '-L',
-# without the need to add '--', even though -L is also an option.)
-# TODO: cope with empty removal
-if thisshellhas [[; then
-	# Use [[ if available because it's generally faster and more robust;
-	# this also avoids BUG_TESTPAREN in zsh 5.0.6/5.0.7 which makes it
-	# impossible for test/[ to check for files named '(', ')' or '!'.
-	# Drawback: can't pass operator through parameter except with 'eval'.
-	_Msh_fileTest() {
-		case ${#},${3-} in
-		( 3,* )		eval "[[ ! -L \$3 && -$2 \$3 ]]" ;;
-		( 4,-L )	eval "[[ -$2 \$4 ]]" ;;
-		( 4,-* )	die "$1: invalid option: $3" || return ;;
-		( 4,* )		die "$1: only one non-option argument allowed" || return ;;
-		( * )		_Msh_dieArgs "$1" "$((${#}-2))" '1 or 2' || return ;;	# BUG_HASHVAR workaround: '${#}'
-		esac
-	}
-else
-	_Msh_fileTest() {
-		case ${#},${3-} in
-		( 3,* )		[ ! -L "$3" ] && [ "-$2" "$3" ] ;;
-		( 4,-L )	[ "-$2" "$4" ] ;;
-		( 4,-* )	die "$1: invalid option: $3" || return ;;
-		( 4,* )		die "$1: only one non-option argument allowed" || return ;;
-		( * )		_Msh_dieArgs "$1" "$((${#}-2))" '1 or 2' || return ;;	# BUG_HASHVAR workaround: '${#}'
-		esac || { let "$? > 1" && die "$1: '[' failed"; }
-	}
-fi
-
-# Test if file descriptor is open and associated with a terminal.
-# (Note: POSIX specifies that file descriptors can be 0 to minimum 19,
-# but most shells only support file descriptors between 0 and 9.)
-if thisshellhas [[; then
-	isonterminal() {
-		case ${#},${1-} in
-		( 1,*[!0123456789]* )
-			die "isonterminal: invalid file descriptor: $1" ;;
-		( 1,* )	[[ -t $1 ]] ;;
-		( * )	_Msh_dieArgs isonterminal "$#" 1 ;;
-		esac
-	}
-elif thisshellhas BUG_TESTILNUM; then
-	# On dash, BUG_TESTILNUM causes test/[ to be misparsed once after
-	# [ -t "$1" ] is called with an invalid number. As a workaround,
-	# we need a dummy invocation of [ to restore correct parsing.
-	isonterminal() {
-		case ${#},${1-} in
-		( 1,*[!0123456789]* )
-			die "isonterminal: invalid file descriptor: $1" ;;
-		( 1,* )	[ -t "$1" ]
-			case $? in
-			( 0 )	;;
-			( 1 )	return 1 ;;
-			( * )	[ 2 -gt 1 ] 2>/dev/null	# BUG_TESTILNUM workaround
-				die "isonterminal: '[' failed" ;;
+		( 1 )	case $1 in
+			( read | write | exec | traverse )
+				# removed empty argument: return false
+				return 1 ;;
+			( * )	die "can: invalid operator: $1" ;;
 			esac ;;
-		( * )	_Msh_dieArgs isonterminal "$#" 1 ;;
+		( 2 )	case $1 in
+			( read )
+				if	[ -d "$2" ] || { let "$? > 1" && { die "can read: '[ -d' failed" || return; }; }
+				then	[ -r "$2" ] && [ -x "$2" ]
+				else	[ -r "$2" ]
+				fi ;;
+			( write )
+				if	[ -d "$2" ] || { let "$? > 1" && { die "can write: '[ -d' failed" || return; }; }
+				then	[ -w "$2" ] && [ -x "$2" ]
+				else	[ -w "$2" ]
+				fi ;;
+			( exec )
+				[ -x "$2" ] && ! [ -d "$2" ] ;;
+			( traverse )
+				[ -x "$2" ] && [ -d "$2" ] ;;
+			( * )	die "can: invalid operator: $1" || return ;;
+			esac || { let "$? > 1" && die "can: '[' failed"; } ;;
+		( * )	_Msh_dieArgs can "$#" '1 or 2' ;;
 		esac
 	}
-else
-	isonterminal() {
-		case ${#},${1-} in
-		( 1,*[!0123456789]* )
-			die "isonterminal: invalid file descriptor: $1" ;;
-		( 1,* )	[ -t "$1" ] || { let "$? > 1" && die "isonterminal: '[' failed"; } ;;
-		( * )	_Msh_dieArgs isonterminal "$#" 1 ;;
+	is() {
+		case $# in
+		( 1 )	case $1 in
+			( reg | dir | sym | fifo | socket | blockspecial | charspecial \
+			setuid | setgid | mine | mygroup )
+				# removed empty argument: return false
+				return 1 ;;
+			( * )	die "is: invalid operator: $1" || return ;;
+			esac ;;
+		( 2 )	case $1 in
+			( reg )	[ ! -L "$2" ] && [ -f "$2" ] ;;
+			( dir )	[ ! -L "$2" ] && [ -d "$2" ] ;;
+			( sym )	[ -L "$2" ] ;;
+			( fifo )
+				[ ! -L "$2" ] && [ -p "$2" ] ;;
+			( socket )
+				[ ! -L "$2" ] && [ -S "$2" ] ;;
+			( blockspecial )
+				[ ! -L "$2" ] && [ -b "$2" ] ;;
+			( charspecial )
+				[ ! -L "$2" ] && [ -c "$2" ] ;;
+			( nonempty )
+				if [ -d "$2" ] || { let "$? > 1" && { die "is nonempty: '[ -d' failed" || return; }; }; then
+					[ -r "$2" ] && [ -x "$2" ] || { let "$? > 1" && { die "is nonempty: '[' failed" || return; } || return 2; }
+					case $- in
+					( *f* ) set +f; set -- "$2" "$2"/[*] "$2"/* "$2"/.[!.]* "$2"/.??*; set -f ;;
+					( * )	set -- "$2" "$2"/[*] "$2"/* "$2"/.[!.]* "$2"/.??* ;;
+					esac
+					case "${#} $2 $3 $4 $5" in
+					( "5 $1/[*] $1/* $1/.[!.]* $1/.??*" )
+						return 1 ;;
+					esac
+				else
+					_Msh_fileTest isnonempty s -L "$@"
+				fi ;;
+			( setuid )
+				[ -u "$2" ] ;;
+			( setgid )
+				[ -g "$2" ] ;;
+			( mine )
+				[ -O "$2" ] ;;
+			( mygroup )
+				[ -G "$2" ] ;;
+			( onterminal )
+				# TODO: reinstate BUG_TESTILNUM workaround
+				case $2 in
+				( *[!0123456789]* )
+					die "is onterminal: invalid file descriptor: $2" || return ;;
+				( * )	[ -t "$2" ] ;;
+				esac ;;
+			( -L )	case $2 in
+				( reg | dir | sym | fifo | socket | blockspecial | charspecial )
+					# removed empty argument: return false
+					return 1 ;;
+				( * )	die "is -L: invalid operator: $2" || return ;;
+				esac ;;
+			( * )	die "is: invalid operator: $1" || return ;;
+			esac || { let "$? > 1" && die "is: '[' failed"; } ;;
+		( 3 )	case $1 in
+			( -L )	case $2 in
+				( reg )	[ -f "$3" ] ;;
+				( dir )	[ -d "$3" ] ;;
+				( sym )	[ -L "$3" ] && [ -e "$3" ] ;;	# "is -L sym": test if valid symlink. TODO: is this logical?
+				( fifo )
+					[ -p "$3" ] ;;
+				( socket )
+					[ -S "$3" ] ;;
+				( blockspecial )
+					[ -b "$3" ] ;;
+				( charspecial )
+					[ -c "$3" ] ;;
+				( * )	die "is -L: invalid operator: $2" || return ;;
+				esac || { let "$? > 1" && die "is -L : '[' failed"; } ;;
+			( * )	die "is: invalid arguments" || return ;;
+			esac ;;
+		( * )	_Msh_dieArgs is "$#" '1 or 2' || return ;;
 		esac
 	}
 fi
