is onsamefs: fixes and simplification
bin/modernish: is onsamefs:
- On non-pathname arguments, prepend $PWD/ so we can strip the last
  element if it's not a directory (is onsamefs), or if it's not a
  directory or valid symlink (is -L onsamefs).
  For instance, Mac and BSD don't like 'df -P /dev/null' so the
  /null needs to be stripped to keep 'df' from failing. Previously
  this did not work with (cd /dev; is onsamefs null /some/file)
- For 'is -L onsamefs', we can't strip the last element if it's a
  valid symlink as we need 'df' to resolve that symlink. However,
  if an argument is a symlink to a block or special character
  device, 'df' on Mac and BSD complain that "raw devices are not
  supported" and fails. To remedy that, substitute any symlink to a
  block or special character device by its target before stripping
  the last element. (Since 'readlink' is neither universal nor
  standard, we must use 'ls -ld'; contrary to received wisdom,
  there is a way to parse it robustly to read a symlink target.)
- Compare not just the file system name but also the mount point,
  reason being that several file systems can share a fs name.
  https://www.mail-archive.com/austin-group-l@opengroup.org/msg01699.html
- Abandon the GNU 'stat' method as it cannot output the mount
  point. On the plus side, the internal function is simpler now.
- Remove extraneous quoting from the [[ variant.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -4577,13 +4577,17 @@ if thisshellhas --rw=[[; then
 				( * )	return 1 ;;
 				esac ;;
 			( onsamefs )
+				# Make sure we have path names so we can strip the last element.
+				[[ $2 != */* ]] && set -- "$1" "$PWD/$2" "$3"
+				[[ $3 != */* ]] && set -- "$1" "$2" "$PWD/$3"
 				# Return false if either of the items does not exist.
-				[[ -e "$2" || -L "$2" ]] || return
-				[[ -e "$3" || -L "$3" ]] || return
-				# We want to keep directories. Remove symlinks and any other type.
-				[[ ! -d "$2" || -L "$2" ]] && set -- "$1" "${2%/*}" "$3"
-				[[ ! -d "$3" || -L "$3" ]] && set -- "$1" "$2" "${3%/*}"
-				_Msh_testOnSameFs "${2:-/}" "${3:-/}" ;;
+				[[ -e $2 || -L $2 ]] || return
+				[[ -e $3 || -L $3 ]] || return
+				# We want to keep directories. Strip symlinks and any other type.
+				[[ ! -d $2 || -L $2 ]] && set -- "$1" "${2%/*}" "$3"
+				[[ ! -d $3 || -L $3 ]] && set -- "$1" "$2" "${3%/*}"
+				# Do the test if the stripped paths are different.
+				[[ ${2:-/} == "${3:-/}" ]] || _Msh_doIsOnSameFs "${2:-/}" "${3:-/}" ;;
 			( * )	die "is: invalid arguments" ;;
 			esac ;;
 		( 4 )	case $1 in
@@ -4595,14 +4599,33 @@ if thisshellhas --rw=[[; then
 				( samefile )
 					[[ $3 -ef $4 ]] ;;
 				( onsamefs )
+					# Make sure we have path names so we can strip the last element.
+					[[ $3 != */* ]] && set -- "$1" "$2" "$PWD/$3" "$4"
+					[[ $4 != */* ]] && set -- "$1" "$2" "$3" "$PWD/$4"
 					# Return false if either of the items does not exist.
-					[[ -e "$3" || -L "$3" ]] || return
-					[[ -e "$4" || -L "$4" ]] || return
+					[[ -e $3 || -L $3 ]] || return
+					[[ -e $4 || -L $4 ]] || return
+					# If we have a symlink to a blockspecial or charspecial device, we must
+					# substitute the target of the link before stripping its final element to
+					# keep "df -P" on Mac and BSD happy.
+					if [[ -L $3 && (-b $3 || -c $3) ]]; then
+						set -- "$1" "$2" "$(POSIXLY_CORRECT=y PATH=$DEFPATH command ls -ld -- "$3"
+							put X)" "$4" "$3"
+						set -- "$1" "$2" "${3%${CCn}X}" "$4" "$5"
+						set -- "$1" "$2" "${3#*" $5 -> "}" "$4"
+					fi
+					if [[ -L $4 && (-b $4 || -c $4) ]]; then
+						set -- "$1" "$2" "$3" "$(POSIXLY_CORRECT=y PATH=$DEFPATH command ls -ld -- "$4"
+							put X)" "$4"
+						set -- "$1" "$2" "$3" "${4%${CCn}X}" "$5"
+						set -- "$1" "$2" "$3" "${4#*" $5 -> "}"
+					fi
 					# We want to keep directories and valid symlinks.
-					# Remove invalid symlinks and any other type.
-					[[ ! -d "$3" && ! ( -L "$3" && -e "$3" ) ]] && set -- "$1" "$2" "${3%/*}" "$4"
-					[[ ! -d "$4" && ! ( -L "$4" && -e "$4" ) ]] && set -- "$1" "$2" "$3" "${4%/*}"
-					_Msh_testOnSameFs "${3:-/}" "${4:-/}" ;;
+					# Strip invalid symlinks and any other type.
+					[[ ! -d $3 && ! (-L $3 && -e $3) ]] && set -- "$1" "$2" "${3%/*}" "$4"
+					[[ ! -d $4 && ! (-L $4 && -e $4) ]] && set -- "$1" "$2" "$3" "${4%/*}"
+					# Do the test if the stripped paths are different.
+					[[ ${3:-/} == "${4:-/}" ]] || _Msh_doIsOnSameFs "${3:-/}" "${4:-/}" ;;
 				( * )	die "is -L: invalid operator: $3" || return ;;
 				esac ;;
 			( * )	die "is: invalid arguments" || return ;;
@@ -4765,13 +4788,17 @@ else
 				( * )	return 1 ;;
 				esac ;;
 			( onsamefs )
+				# Make sure we have path names so we can strip the last element.
+				case $2 in (*/*) ;; (*) set -- "$1" "$PWD/$2" "$3" ;; esac
+				case $3 in (*/*) ;; (*) set -- "$1" "$2" "$PWD/$3" ;; esac
 				# Return false if either of the items does not exist.
 				test -e "$2" || test -L "$2" || return
 				test -e "$3" || test -L "$3" || return
-				# We want to keep directories. Remove symlinks and any other type.
+				# We want to keep directories. Strip symlinks and any other type.
 				{ ! test -d "$2" || test -L "$2"; } && set -- "$1" "${2%/*}" "$3"
 				{ ! test -d "$3" || test -L "$3"; } && set -- "$1" "$2" "${3%/*}"
-				_Msh_testOnSameFs "${2:-/}" "${3:-/}" ;;
+				# Do the test if the stripped paths are different.
+				case ${2:-/} in ("${3:-/}") ;; ( * ) _Msh_doIsOnSameFs "${2:-/}" "${3:-/}" ;; esac ;;
 			( * )	die "is: invalid arguments" || return ;;
 			esac ;;
 		( 4 )	case $1 in
@@ -4783,14 +4810,33 @@ else
 				( samefile )
 					test "$3" -ef "$4" ;;
 				( onsamefs )
+					# Make sure we have path names so we can strip the last element.
+					case $3 in (*/*) ;; (*) set -- "$1" "$2" "$PWD/$3" "$4" ;; esac
+					case $4 in (*/*) ;; (*) set -- "$1" "$2" "$3" "$PWD/$4" ;; esac
 					# Return false if either of the items does not exist.
 					test -e "$3" || test -L "$3" || return
 					test -e "$4" || test -L "$4" || return
+					# If we have a symlink to a blockspecial or charspecial device, we must
+					# substitute the target of the link before stripping its final element to
+					# keep "df -P" on Mac and BSD happy.
+					if test -L "$3" && { test -b "$3" || test -c "$3"; }; then
+						set -- "$1" "$2" "$(POSIXLY_CORRECT=y PATH=$DEFPATH command ls -ld -- "$3"
+							put X)" "$4" "$3"
+						set -- "$1" "$2" "${3%${CCn}X}" "$4" "$5"
+						set -- "$1" "$2" "${3#*" $5 -> "}" "$4"
+					fi
+					if test -L "$4" && { test -b "$4" || test -c "$4"; }; then
+						set -- "$1" "$2" "$3" "$(POSIXLY_CORRECT=y PATH=$DEFPATH command ls -ld -- "$4"
+							put X)" "$4"
+						set -- "$1" "$2" "$3" "${4%${CCn}X}" "$5"
+						set -- "$1" "$2" "$3" "${4#*" $5 -> "}"
+					fi
 					# We want to keep directories and valid symlinks.
-					# Remove invalid symlinks and any other type.
+					# Strip invalid symlinks and any other type.
 					! test -d "$3" && ! { test -L "$3" && test -e "$3"; } && set -- "$1" "$2" "${3%/*}" "$4"
 					! test -d "$4" && ! { test -L "$4" && test -e "$4"; } && set -- "$1" "$2" "$3" "${4%/*}"
-					_Msh_testOnSameFs "${3:-/}" "${4:-/}" ;;
+					# Do the test if the stripped paths are different.
+					case ${3:-/} in ("${4:-/}") ;; ( * ) _Msh_doIsOnSameFs "${3:-/}" "${4:-/}" ;; esac ;;
 				( * )	die "is -L: invalid operator: $3" || return ;;
 				esac ;;
 			( * )	die "is: invalid arguments" || return ;;
@@ -4799,51 +4845,20 @@ else
 		esac
 	}'
 fi
-_Msh_testOnSameFs() {
-	# Stuff for 'is onsamefs' and 'is -L onsamefs': figure out a command that gives us the
-	# names of the file systems that two files reside on. GNU 'stat' or 'gstat' is the most
-	# robust and straightforward. On POSIX systems, we have to parse the output of 'df -P'
-	# to isolate the file systems, which isn't 100% robust, though we can get about 99.9%
-	# of the way there by being really clever with 'sed'. A sanity check is done that kills
-	# the program in case the output isn't exactly two lines.
-	#
-	# Note: this function initialises itself on first use, replacing itself with the result.
-	{ _Msh_is=$(export LC_ALL=C
-		unset -f gstat stat	# QRK_EXECFNBI comat
-		command -v gstat && exec gstat --file-system --format=%i,%t --version
-		command -v stat && exec stat --file-system --format=%i,%t --version); } 2>/dev/null
-	case ${_Msh_is} in
-	( /*/*"stat${CCn}stat (GNU coreutils)"*"Free Software Foundation"* )
-		# We can use GNU 'stat', which is straightforward and secure.
-		_Msh_is=${_Msh_is%%"${_Msh_is#/*/*"stat$CCn"}"}		# "
-		_Msh_is=${_Msh_is%"$CCn"}
-		shellquote _Msh_is	# path to command
-		_Msh_is="export LC_ALL=C POSIXLY_CORRECT=Y
-			exec ${_Msh_is} --file-system --format=%i,%t -- \"\$1\" \"\$2\"" ;;
-	( * )	# We must use POSIX "df -P" and isolate the filesystem names as robustly as possible.
-		# Credit to Geoff Clare: https://www.mail-archive.com/austin-group-l@opengroup.org/msg01681.html
-		_Msh_is='export LC_ALL=C POSIXLY_CORRECT=Y "PATH=$DEFPATH"
-			unset -f df sed  # QRK_EXECFNBI compat
-			exec df -P -- "$1" "$2" | exec sed "1d;s/\([[:blank:]]\{1,\}[[:digit:]]\{1,\}\)\{4\}%[[:blank:]].*//"' ;;
+_Msh_doIsOnSameFs() {
+	# Invoke POSIX "df -P" and isolate the file system names and mount points as reliably as possible.
+	# Ref. (thread): https://www.mail-archive.com/austin-group-l@opengroup.org/msg01699.html
+	_Msh_is=$(export LC_ALL=C POSIXLY_CORRECT=y "PATH=$DEFPATH"
+		unset -f df sed  # QRK_EXECFNBI compat
+		exec df -P -- "$1" "$2" | exec sed '1d; s/\([[:blank:]]\{1,\}[[:digit:]]\{1,\}\)\{4\}%[[:blank:]]\{1,\}/,/')
+	# If the two lines are identical, the files are on the same filesystem.
+	case ${_Msh_is#*$CCn} in
+	( *$CCn* | "${_Msh_is}" )  # >2 lines or 1 line
+		die "is onsamefs: internal error" || return ;;
+	( "${_Msh_is%$CCn*}" )
+		unset -v _Msh_is ;;
+	( * )	! unset -v _Msh_is ;;
 	esac
-	eval '_Msh_testOnSameFs() {
-		_Msh_is=$('"${_Msh_is}"')
-		# Sanity check: verify that exactly 2 lines were produced.
-		case ${_Msh_is} in
-		( *"$CCn"*"$CCn"* )
-			die "is onsamefs: internal error 1" || return ;;
-		( *"$CCn"* ) ;;
-		( * )	die "is onsamefs: internal error 2" || return ;;
-		esac
-		# If the two lines are identical, the files are on the same filesystem.
-		case ${_Msh_is#*"$CCn"} in
-		( "${_Msh_is%%"$CCn"*}" )
-			unset -v _Msh_is ;;
-		( * )	! unset -v _Msh_is ;;
-		esac
-	}'
-	thisshellhas ROFUNC && readonly -f _Msh_testOnSameFs
-	_Msh_testOnSameFs "$@"
 }
 
 # -------------
