chdir(): support -L and -P, with -P as the default
There is a use case for robust 'chdir' without the CDPATH and arbitrary
pathname issues but also without resolving symlinks (logical traversal).
So let's support cd's -L and -P options, but with -P as the default.

bin/modernish: chdir():
- Add support for -L and -P.
- Support combined options like 'chdir -fL'.

README.md:
- Document -L and -P.
- Copy-edit.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -596,13 +596,21 @@ _Msh_doExit() {
 # Robust 'cd' replacement for use in scripts. Standard 'cd' suffers from pitfalls with symlinks
 # and inheritance of $CDPATH, and cannot safely be used with arbitrary directory names. Robust
 # and portable use of 'cd' in scripts is unreasonably difficult. Hence this wrapper function.
-# Usage: chdir [ -f ] -- <directory>
+# Usage: chdir [ -fLP ] -- <directory>
 # The -f option tolerates failure.
+# -L and -P are as in 'cd', except that -P is the default.
 chdir() {
-	unset -v _Msh_chdir_f
+	unset -v _Msh_cD_f _Msh_cD_L
 	while	case ${1-} in
+		( -f )	_Msh_cD_f= ;;
+		( -L )	_Msh_cD_L=L ;;
+		( -P )	unset -v _Msh_cD_L ;;
 		( -- )	shift; break ;;
-		( -f )	_Msh_chdir_f= ;;
+		( -[!-]?* ) # split a set of combined options
+			_Msh_cD__o=${1#-}; shift
+			while ! str empty "${_Msh_cD__o}"; do
+				set -- "-${_Msh_cD__o#"${_Msh_cD__o%?}"}" "$@"; _Msh_cD__o=${_Msh_cD__o%?}	#"
+			done; unset -v _Msh_cD__o; continue ;;
 		( -* )	die "chdir: invalid option: $1" ;;
 		( * )	break ;;
 		esac
@@ -618,11 +626,11 @@ chdir() {
 	( 1,* )	set -- "./$1" ;;
 	( * )   die "chdir: need 1 operand, got $#" ;;
 	esac
-	case ${_Msh_chdir_f+f} in
-	( f )	unset -v _Msh_chdir_f
-		CDPATH='' command cd -P -- "$1" || return 1 ;;
-	( * )	CDPATH='' command cd -P -- "$1" || die "chdir: failed to change directory to '$1'" ;;
-	esac
+	if ! CDPATH='' command cd "-${_Msh_cD_L:-P}" -- "$1"; then
+		isset _Msh_cD_f && unset -v _Msh_cD_f _Msh_cD_L && return 1
+		die "chdir: failed to change directory to '$1'"
+	fi
+	unset -v _Msh_cD_f _Msh_cD_L
 }
 
 # Manually set exit status ("$?") to the desired value. The canonical method
