BUG_WAITST: 'wait' does not reliably acquire bg job's exit status
bin/modernish:
- Detect BUG_WAITST as a side effect of discovering $SIGPIPESTATUS.
  If the exit status is less than 128, assume 'wait' didn't do its
  job properly.
- Hard-code BUG_WAITST for Bash 2.x. The version checking is
  unavoidable because the bug occurs intermittently on that shell
  due to a race condition.
- More precise 'case' pattern to check for FTL_SIGPIPEST.

README.md:
- Document BUG_WAITST.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -870,30 +870,34 @@ esac
 # According to POSIX, the numerical value of SIGPIPE is implementation-defined. In addition, different
 # shells have different exit status offsets for signals: yash has signum+384, ksh93 has signum+256, the
 # rest signum+128. So we have to kill a process with SIGPIPE to find out its exit status.
-case ${-},${BASH_VERSION-} in
-( *m*,* | *,2.* )
-	# ^^^^^ (bash 2 has a race condition with 'kill $!' that means we need to avoid the other method.)
-	# Slow but reliable method.
+case $- in
+( *m* )	# Slow but reliable method.
 	"$MSH_SHELL" -c 'kill -s PIPE $$ || kill -PIPE $$'
 	SIGPIPESTATUS=$? ;;
 ( * )	# Fastest method because 'kill' will normally kill the background job before it even starts running.
 	# Use it only with job control disabled to avoid job control clutter on the terminal.
-	"$MSH_SHELL" -c ':' & kill -s PIPE "$!"
-	wait "$!"	# acquire exit status from background job
-	SIGPIPESTATUS=$?
+	case ${BASH_VERSION-} in
+	( 2.* )	# bash 2 has a race condition with 'wait' that means we need to avoid this method.
+		# 'wait' may either exit shell with "Broken pipe" or set exit status to 0.
+		SIGPIPESTATUS=0 ;;
+	( * )	"$MSH_SHELL" -c ':' & kill -s PIPE "$!"
+		wait "$!"	# acquire exit status from background job
+		SIGPIPESTATUS=$? ;;
+	esac
 	case $SIGPIPESTATUS in
 	( ? | ?? | 1[01]? | 12[!9] )
 		# - A race condition on some old shells may cause "wait $!" to yield status 0.
 		# - An obscure intermittent bug on AT&T ksh93 may cause the exit status of "wait $!" to
 		#   be 13 (the value of SIGPIPE without the mandatory offset), depending on the version.
+		_Msh_have BUG_WAITST
 		# Fall back to the simple method for these cases, or any others where $? <= 128.
 		"$MSH_SHELL" -c 'kill -s PIPE $$ || kill -PIPE $$'
 		SIGPIPESTATUS=$? ;;
 	esac ;;
 esac 2>/dev/null
 case $SIGPIPESTATUS in
-( ??? )	;;
-( * )	_Msh_have FTL_SIGPIPEST "Can't determine SIGPIPESTATUS (bad value: $SIGPIPESTATUS)"
+( ? | ?? | 1[01]? | 12[!9] )
+	_Msh_have FTL_SIGPIPEST "Can't determine SIGPIPESTATUS (bad value: $SIGPIPESTATUS)" ;;
 esac
 readonly SIGPIPESTATUS
 
