insubshell -p: get the PID of the current (sub)shell
bin/modernish:
- getmyshellpid(): Removed. Unused, undocumented, unfinished.
- insubshell(): Add -p option integrating the functionality of the
  former getmyshellpid(), but more reliable and adaptive. If -p
  is given, insubshell() now leaves the PID of the current
  (sub)shell in RPELY.

libexec/modernish/tests/insubshell.t
- Test the new option. (Test 7 notes if the shell does subshells
  without forking a new process, which would be ksh93).

README.md:
- Update insubshell() documentation.

share/doc/modernish/SHELLBUGS b/share/doc/modernish/SHELLBUGS:
- Move documentation on buggy $BASH_SUBSHELL (which we're not
  using) from bin/modernish comments to here.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1544,38 +1544,37 @@ fi
 # -------------
 
 # insubshell: Check if we're currently running in a subshell.
-# Usage:	insubshell
+# Usage:	insubshell [ -p ]
 # Returns with status 0 if we're in a subshell, 1 if not.
-# The canonical method involves exec'ing a shell and is slow, so try hard to
+# If -p is given, leaves the PID of the current (sub)shell in $REPLY.
+#
+# The generic method involves exec'ing a shell and is slow, so try hard to
 # determine an efficient shell-specific version.
-_Msh_inSbSh_canonical='# The following should always work if $MSH_SHELL was determined by the installer.
-	case $(exec "$MSH_SHELL" -c "echo \$PPID") in
-	( "$$" ) return 1 ;;
-	( "" | *[!0123456789]* )   ;;
-	( * )	 return 0 ;;
+_Msh_inSbSh_generic='# The following should always work if $MSH_SHELL was determined by the installer.
+	_Msh_inSbSh_P=$(exec "$MSH_SHELL" -c "echo \$PPID")
+	case ${_Msh_inSbSh_P} in
+	( "" | *[!0123456789]* )
+		# No or invalid output? Slower fallback: get even an ancient Bourne shell to emulate $PPID with "ps".
+		# (This occurs on NetBSD and Minix when a non-installed copy runs, defaulting to /bin/sh with no $PPID)
+		_Msh_inSbSh_P=$(PATH=$DEFPATH exec sh -c '\''ppid=`ps -o ppid= -p $$` && echo $ppid'\'') ;;
 	esac
-	# No or invalid output? Slower fallback: get a shell to emulate $PPID with "ps" and "awk".
-	# (This occurs on NetBSD and Minix when a non-installed copy runs, defaulting to /bin/sh with no $PPID)
-	case $(PATH=$DEFPATH exec sh -c '\''ps -A -o ppid -o pid | awk "{ if (\$2==$$) print \$1 }"'\'') in
-	( "$$" ) return 1 ;;
-	( "" | *[!0123456789]* )   ;;
-	( * )	 return 0 ;;
-	esac
-	# Give up and die. But we cannot simply call die() here because it uses insubshell(): infinite loop
-	putln "${ME##*/}: insubshell: internal error: cannot determine parent PID! Reinstall modernish." 1>&2
-	if isset -i; then
-		PATH=$DEFPATH command kill -s INT "$$"
-		command exit 125
-	elif isset _Msh_die_isrunning; then
-		return 0
-	else
-		die
-	fi'
-# [Note: On bash, $BASH_SUBSHELL is buggy: bash up to 4.4.0 resets BASH_SUBSHELL to 0 in a
-# subshell EXIT trap. Since the trap stack depends on this function to deactivate itself in a
-# subshell, we can't be having that. As of bash 4 (and on mksh) we can use $BASHPID instead.
-# Even when bash fixes the $BASH_SUBSHELL bug, there will never be a bash version without
-# $BASHPID but a non-buggy $BASH_SUBSHELL, so modernish will never need to use $BASH_SUBSHELL.]
+	case ${#},${_Msh_inSbSh_P} in
+	( ?,"" | ?,*[!0123456789]* )
+		# Give up and die. But we cannot simply call die() here because it uses insubshell(): infinite loop
+		putln "${ME##*/}: insubshell: internal error: cannot determine parent PID" 1>&2
+		if isset -i; then
+			PATH=$DEFPATH command kill -s INT "$$"
+			command exit 125
+		elif isset _Msh_die_isrunning; then
+			return 0
+		else
+			die
+		fi ;;
+	( "0,$$" ) unset -v _Msh_inSbSh_P; return 1 ;;
+	( "1,$$" ) REPLY=$$; unset -v _Msh_inSbSh_P; return 1 ;;
+	( 0,* )    unset -v _Msh_inSbSh_P; return 0 ;;
+	( 1,* )    REPLY=${_Msh_inSbSh_P}; unset -v _Msh_inSbSh_P; return 0 ;;
+	esac'
 if isset BASHPID &&
 	_Msh_test=$BASHPID &&
 	case $(command trap 'command -p echo "$((BASHPID != _Msh_test))"' EXIT;
@@ -1586,7 +1585,8 @@ if isset BASHPID &&
 	esac
 then	# bash 4 and mksh
 	# note inverted comparison: true = 1 = return false
-	_Msh_inSbSh_method='return "$((BASHPID == $$))"'
+	_Msh_inSbSh_method='case $# in ( 1 ) return "$(((REPLY = BASHPID) == $$))" ;; esac
+		return "$((BASHPID == $$))"'
 elif isset ZSH_VERSION && isset ZSH_SUBSHELL &&
 	_Msh_test=$ZSH_SUBSHELL &&
 	case $(command trap 'command -p echo "$((ZSH_SUBSHELL != _Msh_test))"' EXIT;
@@ -1595,10 +1595,13 @@ elif isset ZSH_VERSION && isset ZSH_SUBSHELL &&
 	( * )		unset -v ZSH_SUBSHELL || _Msh_initExit "can't unset non-working ZSH_SUBSHELL!"
 			! : ;;
 	esac
-then	# zsh
-	_Msh_inSbSh_method='case $ZSH_SUBSHELL in
-		( 0 ) return 1 ;;
-		esac'
+then	# zsh: $ZSH_SUBSHELL can tell us whether we're in a subshell, but not its PID, so fall back to generic for that.
+	_Msh_inSbSh_method='case ${#},${ZSH_SUBSHELL} in
+		( 0,0 ) return 1 ;;
+		( 0,* ) return 0 ;;
+		( 1,0 ) REPLY=$$; return 1 ;;
+		esac
+		'"${_Msh_inSbSh_generic}"
 elif thisshellhas KSH93FUNC && (eval ': ${.sh.subshell}') 2>/dev/null; then
 	# AT&T ksh93. It does non-background subshells without forking a new process, so the default version
 	# won't work correctly. It has an internal ${.sh.subshell} counter that is increased each time a
@@ -1617,58 +1620,36 @@ elif thisshellhas KSH93FUNC && (eval ': ${.sh.subshell}') 2>/dev/null; then
 				"this is a fatal problem. Please report."
 		fi
 		_Msh_inSbSh_dummyFunc() { :; }
-		_Msh_inSbSh_method='unset -f _Msh_inSbSh_dummyFunc
+		_Msh_inSbSh_method='(($#)) && REPLY=$$
+			unset -f _Msh_inSbSh_dummyFunc
 			if isset -f _Msh_inSbSh_dummyFunc; then
 				# Due to BUG_FNSUBSH, if we cannot unset the function, we are in a non-background subshell!
 				return 0
 			fi
 			# Set the function again for future checks.
 			_Msh_inSbSh_dummyFunc() { :; }
-			# Now use the canonical method to check if this is a background subshell.
-			'"${_Msh_inSbSh_canonical}"
+			# Now use the generic method to check if this is a background subshell.
+			'"${_Msh_inSbSh_generic}"
 	else
 		# We're on AT&T ksh93 without BUG_KSHSUBVAR so we can check ${.sh.subshell}.
-		_Msh_inSbSh_method='# The ${.sh.subshell} parameter only counts non-background subshells.
+		_Msh_inSbSh_method='(($#)) && REPLY=$$
+			# The ${.sh.subshell} parameter only counts non-background subshells.
 			((.sh.subshell)) && return 0
-			# Now use the canonical method to check if this is a background subshell.
-			'"${_Msh_inSbSh_canonical}"
+			# Now use the generic method to check if this is a background subshell.
+			'"${_Msh_inSbSh_generic}"
 	fi
 else	# Default, slow version. We must exec a shell to get it to report our PID back to us.
 	# If modernish was installed properly, $MSH_SHELL is a known-good shell with $PPID.
-	_Msh_inSbSh_method=${_Msh_inSbSh_canonical}
+	_Msh_inSbSh_method=${_Msh_inSbSh_generic}
 fi
 eval 'insubshell() {
-	case $# in
-	( [!0]* ) _Msh_dieArgs insubshell "$#" 0 ;;
+	case ${#},${1-} in
+	( 1,-p )  ;;
+	( [!0]* ) die "insubshell: invalid arguments: $@" || return ;;
 	esac
 	'"${_Msh_inSbSh_method}"'
 }'"${CCn}"
-unset -v _Msh_inSbSh_canonical _Msh_inSbSh_method
-
-# getmyshellpid: Store the process ID of the current subshell in REPLY. Note that this is
-# different from $$, which always contains the main shell's PID, even if you're in a subshell.
-# Also note AT&T ksh93 does non-background subshells without forking a new process.
-if isset BASHPID; then
-	# BASHPID was already tested above and unset if found lacking
-	getmyshellpid() {
-		case $# in
-		( [!0]* ) _Msh_dieArgs getmyshellpid "$#" 0 ;;
-		esac
-		REPLY=$BASHPID
-	}
-else
-	getmyshellpid() {
-		case $# in
-		( [!0]* ) _Msh_dieArgs getmyshellpid "$#" 0 ;;
-		esac
-		REPLY=$(exec "$MSH_SHELL" -c 'echo $PPID')
-		case $REPLY in
-		( '' | 0 ) unset -v REPLY
-		#    ^^^ BUG_ARITHTYPE compat
-			die "currshellpid: internal error: $MSH_SHELL does not have \$PPID! Reinstall modernish." ;;
-		esac
-	}
-fi
+unset -v _Msh_inSbSh_generic _Msh_inSbSh_method
 
 # Unconditionally make these names read-only, in order to:
 # - reserve the names on shells without this functionality, to avoid cross-platform compatibility problems
