is nonempty: new method for directories
Until now, the directory method for 'is nonempty' read an entire
directory using shell globbing; this is a problem if the directory
has a huge number of files in it. Instead, if we use 'find' to read
just the current directory, we can exec a shell to kill 'find' at
the first result found. The exit status can then be used to
determine if the directory is empty or not.

bin/modernish: is(): nonempty:
- Replace method for testing nonemptiness of directory. This
  depends on the signal number for SIGKILL being 9, and the shell
  adding a multiple of 128 to the signal number to calculate the
  exit status. Both assumptions are de facto portable.

lib/modernish/tst/@sanitychecks.t:
- Add check for the assumption that the shell adds some multiple of
  128 to a signal number to calculate the exit status of a process
  terminated by a signal.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -2042,14 +2042,20 @@ if thisshellhas DBLBRACKET; then
 				[[ ! -L $2 && -c $2 ]] ;;
 			( nonempty )
 				if [[ -d $2 ]]; then
-					[[ -r $2 ]] || return 2
-					case $- in
-					( *f* ) set +f
-						set -- "${2%/}" "${2%/}"/[*] "${2%/}"/* "${2%/}"/.[!.]* "${2%/}"/.??*
-						set -f ;;
-					( * )	set -- "${2%/}" "${2%/}"/[*] "${2%/}"/* "${2%/}"/.[!.]* "${2%/}"/.??* ;;
+					# Avoid reading an entire (potentially huge) directory by killing "find" at 1st result.
+					{ (
+						chdir -f -- "$2" || exit 2
+						unset -f find   # QRK_EXECFNBI compat
+						PATH=$DEFPATH exec find . ! -name . -prune \
+							-exec "$MSH_SHELL" -u -c '\''kill -9 "$PPID"'\'' ";"
+					) && :; } 2>/dev/null  # suppress signal messages
+					case $(( ($? >= 128) ? ($? % 128 + 128) : $? )) in
+					( 0 )	return 1 ;;
+					( 137 )	return 0 ;;  # SIGKILL (9 + 128): found something
+					( ? | ?? | 1[01]? | 12[012345] )
+						return 2 ;;  # <= 125: non-fatal error
+					( * )	die "is nonempty: system error executing '\''find'\''" ;;
 					esac
-					[[ "${#} $2 $3 $4 $5" != "5 $1/[*] $1/* $1/.[!.]* $1/.??*" ]]
 				else
 					[[ -s $2 ]]
 				fi ;;
@@ -2241,16 +2247,19 @@ else
 				! test -L "$2" && test -c "$2" ;;
 			( nonempty )
 				if test -d "$2"; then
-					test -r "$2" || return 2
-					case $- in
-					( *f* ) set +f
-						set -- "${2%/}" "${2%/}"/[*] "${2%/}"/* "${2%/}"/.[!.]* "${2%/}"/.??*
-						set -f ;;
-					( * )	set -- "${2%/}" "${2%/}"/[*] "${2%/}"/* "${2%/}"/.[!.]* "${2%/}"/.??* ;;
-					esac
-					case "${#} $2 $3 $4 $5" in
-					( "5 $1/[*] $1/* $1/.[!.]* $1/.??*" )
-						return 1 ;;
+					# Avoid reading an entire (potentially huge) directory by killing "find" at 1st result.
+					{ (
+						chdir -f -- "$2" || exit 2
+						unset -f find   # QRK_EXECFNBI compat
+						PATH=$DEFPATH exec find . ! -name . -prune \
+							-exec "$MSH_SHELL" -u -c '\''kill -9 "$PPID"'\'' ";"
+					) && :; } 2>/dev/null  # suppress signal messages
+					case $(( ($? >= 128) ? ($? % 128 + 128) : $? )) in
+					( 0 )	return 1 ;;
+					( 137 )	return 0 ;;  # SIGKILL (9 + 128): found something
+					( ? | ?? | 1[01]? | 12[012345] )
+						return 2 ;;  # <= 125: non-fatal error
+					( * )	die "is nonempty: system error executing '\''find'\''" ;;
 					esac
 				else
 					test -s "$2"
