harden(): '-p' and '-u' optimisations; bugfix for assignment args
bin/modernish:

- harden -p: Now only add PATH=$DEFPATH as an implicit assignment
  argument if either the command is a shell function, or '-p'
  was specified twice. Always exporting the default PATH may have
  undesired effects. For instance,
	harden -f chown -p sudo chown
  now searches for 'sudo' in the system-default path, but 'sudo'
  will search for 'chown' in the normal user path. Whereas
	harden -f chown -pp sudo chown
  will cause 'sudo' to search for 'chown' in the system-default
  path as well.

- BUGFIX: If the hardening function runs the hardened command
  in a subshell, any variable assignment arguments generated
  an 'export' command in the form of
	export foo=bar baz=quux
  But on basic POSIX shells, those arguments to 'export are
  subject to field splitting and globbing. While the values
  are shellquoted to avoid this, the variable names aren't,
  so if IFS contains any variable name character, this breaks.
  So, now use the more robust classic Bourne shell form:
	foo=bar baz=quux; export foo bar

- Optimisation: if an external command is caused to be run from
  a subshell due to the use of '-u' (i.e. there are variables
  to unset), then run it with 'exec', replacing the subshell
  rather than creating yet another process. (Some shells perform
  this optimisation automatically, but not all do.)

- Rename internal variables so the names are more systematic:
  all the option variables now start with _Msh_Ho_.

README.md:

- Document the change to the '-p' option.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3115,8 +3115,9 @@ alias popparams='{ pop _Msh_PPs && eval "set -- ${_Msh_PPs-}" && { unset -v _Msh
 # function, you have to harden it 'as' a different name.
 unset -v _Msh_Ht_R _Msh_Ht_y _Msh_Ht_r _Msh_Ht_b  # for storing (t)erminal codes for (t)racing
 harden() {
-	# ___begin option parser____
-	unset -v _Msh_Ho_P _Msh_Ho_t _Msh_Ho_p _Msh_H_arg _Msh_H_func _Msh_H_set _Msh_H_unset
+	# ___begin option & assignment argument parser____
+	unset -v _Msh_Ho_P _Msh_Ho_t _Msh_Ho_e _Msh_Ho_f _Msh_Ho_u _Msh_H_V _Msh_H_VA
+	_Msh_Ho_p=0	# count how many times '-p' was specified
 	while :; do
 		case ${1-} in
 		( [!-]*=* ) # environment variable assignment
@@ -3124,7 +3125,8 @@ harden() {
 			isset -r "${1%%=*}" && { die "harden: read-only variable: ${1%%=*}" || return; }
 			_Msh_H_QV=${1#*=}
 			shellquote _Msh_H_QV
-			_Msh_H_set=${_Msh_H_set:+$_Msh_H_set }${1%%=*}=${_Msh_H_QV}
+			_Msh_H_VA=${_Msh_H_VA:+$_Msh_H_VA }${1%%=*}=${_Msh_H_QV}
+			_Msh_H_V=${_Msh_H_V:+$_Msh_H_V }${1%%=*}
 			unset -v _Msh_H_QV ;;
 		( -??* ) # split a set of combined options
 			_Msh_Ho__o=${1#-}
@@ -3157,25 +3159,24 @@ harden() {
 			done
 			unset -v _Msh_Ho__o _Msh_Ho__a
 			continue ;;
-		( -[Ptp] )
+		( -[Pt] )
 			eval "_Msh_Ho_${1#-}=''" ;;
-		( -e )	let "$# > 1" || die "harden: $1: option requires argument" || return
-			shift
-			_Msh_H_arg=$1 ;;
+		( -p )	let "_Msh_Ho_p += 1" ;;
+		( -[ef] )
+			let "$# > 1" || die "harden: $1: option requires argument" || return
+			eval "_Msh_Ho_${1#-}=\$2"
+			shift ;;
 		( -u )	let "$# > 1" || die "harden: $1: option requires argument" || return
-			shift
-			isvarname "$1" || die "harden -u: invalid variable name: $1" || return
-			_Msh_H_unset=${_Msh_H_unset:+$_Msh_H_unset }$1 ;;
-		( -f )	let "$# > 1" || die "harden: $1: option requires argument" || return
-			shift
-			_Msh_H_func=$1 ;;
+			isvarname "$2" || die "harden -u: invalid variable name: $2" || return
+			_Msh_Ho_u=${_Msh_Ho_u:+$_Msh_Ho_u }$2
+			shift ;;
 		( -- )	shift; break ;;
 		( -* )	die "harden: invalid option: $1" || return ;;
 		( * )	break ;;
 		esac
 		shift
 	done
-	# ^^^end option parser^^^
+	# ^^^end option & assignment argument parser^^^
 
 	case $# in
 	( 0 )	die "harden: command expected${CCn}" \
@@ -3183,40 +3184,43 @@ harden() {
 			"${CCt}[ <var=value> ... ] [ -u <var> ... ] <cmdname/path> [ <arg> ... ]" || return ;;
 	esac
 
-	isset _Msh_H_func || _Msh_H_func=$1
-	if isset _Msh_Ho_p; then
+	isset _Msh_Ho_f || _Msh_Ho_f=$1
+	if let "_Msh_Ho_p > 0"; then
 		_Msh_H_cmd=$(command unalias "$1"; PATH=$DEFPATH; command -v -- "$1")
-		_Msh_H_set=${_Msh_H_set:+$_Msh_H_set }PATH=\$DEFPATH
 	else
 		_Msh_H_cmd=$(command unalias "$1"; command -v -- "$1")
 	fi 2>/dev/null
 
 	case ${_Msh_H_cmd} in
-	( '' )	die "${_Msh_H_C-harden}${_Msh_Ho_p+ -p}: command not found: '$1'" || return ;;
+	( '' )	if let "_Msh_Ho_p > 0"; then
+			die "${_Msh_H_C-harden} -p: command not found in system default path: '$1'"
+		else
+			die "${_Msh_H_C-harden}: command not found: '$1'"
+		fi || return ;;
 	esac
-	case ${_Msh_H_func} in
+	case ${_Msh_Ho_f} in
 	(\!|\{|\}|case|do|done|elif|else|\esac|fi|for|if|in|then|until|while \
 	|break|:|continue|.|eval|exec|exit|export|readonly|return|set|shift|times|trap|unset)
 		# blacklist POSIX reserved words and special builtins
-		die "${_Msh_H_C-harden}: can't harden POSIX reserved word or special builtin '${_Msh_H_func}'" || return ;;
+		die "${_Msh_H_C-harden}: can't harden POSIX reserved word or special builtin '${_Msh_Ho_f}'" || return ;;
 	( '' | [0123456789]* | *[!"$ASCIIALNUM"_]* )
-		die "${_Msh_H_C-harden}: invalid shell function name: ${_Msh_H_func}" || return
+		die "${_Msh_H_C-harden}: invalid shell function name: ${_Msh_Ho_f}" || return
 		;;
 	esac
-	if thisshellhas "--rw=${_Msh_H_func}"; then
-		die "${_Msh_H_C-harden}: can't harden reserved word '${_Msh_H_func}'" || return
-	elif alias "${_Msh_H_func}" >/dev/null 2>&1; then
-		die "harden: function name '${_Msh_H_func}' conflicts with alias '${_Msh_H_func}'" || return
+	if thisshellhas "--rw=${_Msh_Ho_f}"; then
+		die "${_Msh_H_C-harden}: can't harden reserved word '${_Msh_Ho_f}'" || return
+	elif alias "${_Msh_Ho_f}" >/dev/null 2>&1; then
+		die "harden: function name '${_Msh_Ho_f}' conflicts with alias '${_Msh_Ho_f}'" || return
 	fi
 
 	# check if setting a function is possible
-	(eval "${_Msh_H_func}() { :; }") 2>/dev/null || die "${_Msh_H_C-harden}: can't harden '${_Msh_H_func}'" || return
+	(eval "${_Msh_Ho_f}() { :; }") 2>/dev/null || die "${_Msh_H_C-harden}: can't harden '${_Msh_Ho_f}'" || return
 
 	unset -v _Msh_H_isFunc
 	case ${_Msh_H_cmd} in
-	( "${_Msh_H_func}" )
-		if isset -f "${_Msh_H_func}"; then
-			die "${_Msh_H_C-harden}: can't harden a shell function as itself: ${_Msh_H_func}" || return
+	( "${_Msh_Ho_f}" )
+		if isset -f "${_Msh_Ho_f}"; then
+			die "${_Msh_H_C-harden}: can't harden a shell function as itself: ${_Msh_Ho_f}" || return
 		fi
 		# Got shell built-in command.
 		_Msh_H_BI="command "
@@ -3237,6 +3241,8 @@ harden() {
 			# and unvalidated input. Aliases could contain any combination of shell grammar and
 			# compound commands, so they could easily mess up the hardening function.
 			die "harden: aliases are not supported: ${_Msh_H_cmd}" || return
+		elif isset -f "${_Msh_Ho_f}"; then
+			die "harden -f: function already exists: ${_Msh_Ho_f}" || return
 		elif isset -f "${_Msh_H_cmd}"; then
 			_Msh_H_BI=''
 			_Msh_H_isFunc=y
@@ -3247,6 +3253,12 @@ harden() {
 		fi
 		;;
 	esac
+
+	# two '-p' options, or shell function and one '-p' option: also export PATH=$DEFPATH for this command
+	if let "_Msh_Ho_p > 1" || { isset _Msh_H_isFunc && let "_Msh_Ho_p > 0"; }; then
+		_Msh_H_VA=${_Msh_H_VA:+$_Msh_H_VA }PATH=\$DEFPATH
+		_Msh_H_V=${_Msh_H_V:+$_Msh_H_V }PATH
+	fi
 
 	# add any extra command arguments (e.g. options)
 	shift
@@ -3287,27 +3299,36 @@ harden() {
 		fi 2>/dev/null
 		if is onterminal 9 && ! empty "${_Msh_Ht_R}"; then
 			# highlight trace in red, yellow and blue with fallback to monochrome highlighting
-			_Msh_Ho_t="putln \"\${_Msh_Ht_y}[\${_Msh_Ht_r}${_Msh_H_func}\${_Msh_Ht_y}]> \${_Msh_Ht_b}\${_Msh_P}\${_Msh_Ht_R}\" 1>&9"
+			_Msh_Ho_t="putln \"\${_Msh_Ht_y}[\${_Msh_Ht_r}${_Msh_Ho_f}\${_Msh_Ht_y}]> \${_Msh_Ht_b}\${_Msh_P}\${_Msh_Ht_R}\" 1>&9"
 		else	# default
-			_Msh_Ho_t="putln \"[${_Msh_H_func}]> \${_Msh_P}\" 1>&9"
+			_Msh_Ho_t="putln \"[${_Msh_Ho_f}]> \${_Msh_P}\" 1>&9"
 		fi
 	fi
 
 	# If we have a builtin, add the 'command -- ' prefix now.
 	# If we have variables to export or unset, add them now.
-	if isset _Msh_H_unset || isset _Msh_H_set; then
-		if isset _Msh_H_unset || isset _Msh_H_isFunc; then
+	if isset _Msh_Ho_u || isset _Msh_H_V; then
+		if isset _Msh_Ho_u || isset _Msh_H_isFunc; then
 			# If it's either a shell function, or it's any kind of command and we have variables to unset,
 			# we have to run it in a ( subshell ) with the indicated variables unset and/or exported.
-			_Msh_E=${_Msh_H_unset:+unset -v $_Msh_H_unset; }${_Msh_H_set:+export $_Msh_H_set; }${_Msh_H_BI}
+			#   [Note: we cannot generate assignment arguments to 'export' (export foo=bar) because, on
+			#   basic POSIX shells, those are subject to field splitting and globbing. So generate the
+			#   assignments and the 'export' command separately.]
+			_Msh_E=${_Msh_Ho_u:+unset -v $_Msh_Ho_u; }${_Msh_H_VA:+$_Msh_H_VA; }${_Msh_H_V:+export $_Msh_H_V; }
+			if ! isset _Msh_H_isFunc; then
+				# use either 'command -- ' for builtin or (since we're in a subshell) 'exec ' for external cmd
+				_Msh_E=${_Msh_E}${_Msh_H_BI:-exec }
+			fi
 			_Msh_H_cmd="( ${_Msh_E}${_Msh_H_cmd} )"
+			# ...for tracing and error messages:
 			_Msh_E="( ${_Msh_E}"
 			shellquote _Msh_E
 			_Msh_H_spp="${_Msh_H_spp} && _Msh_P=${_Msh_E}\${_Msh_P}' )'"
 		else	# If it's a builtin or external command, and we have nothing to unset, we can use
 			# the shell grammar's mechanism for temporarily assigning variables to export.
-			_Msh_E="${_Msh_H_set} ${_Msh_H_BI}"
+			_Msh_E="${_Msh_H_VA} ${_Msh_H_BI}"
 			_Msh_H_cmd="${_Msh_E}${_Msh_H_cmd}"
+			# ...for tracing and error messages:
 			shellquote _Msh_E
 			_Msh_H_spp="${_Msh_H_spp} && _Msh_P=${_Msh_E}\${_Msh_P}"
 		fi
@@ -3320,14 +3341,14 @@ harden() {
 	 unset -f 'command' 'set' 'unset' 'return' 'eval'; } 2>/dev/null
 
 	# determine status checking method and set hardening function
-	if	case ${_Msh_H_arg='>0'} in
+	if	case ${_Msh_Ho_e='>0'} in
 		( '>0' | '> 0' | '>=1' | '>= 1' | '!=0' | '!= 0' ) ;;
 		( * ) ! : ;;
 		esac &&
 		! isset _Msh_Ho_P
 	then	# For efficiency, handle a simple non-zero check specially.
 		if isset _Msh_Ho_t; then
-			eval "${_Msh_H_func}() {
+			eval "${_Msh_Ho_f}() {
 				${_Msh_H_spp}
 				${_Msh_Ho_t}
 				${_Msh_H_cmd} && unset -v _Msh_P || {
@@ -3335,32 +3356,32 @@ harden() {
 					if let '_Msh_E>128' && _Msh_arg2sig \"\${_Msh_E}\"; then
 						_Msh_P=\"killed by SIG\${_Msh_sig}: \${_Msh_P}\"
 					fi
-					die \"${_Msh_H_func}: command failed with status \${_Msh_E}: \${_Msh_P}\"
+					die \"${_Msh_Ho_f}: command failed with status \${_Msh_E}: \${_Msh_P}\"
 					eval \"unset -v _Msh_P _Msh_E; return \${_Msh_E}\"
 				}
 			}${CCn}"
 		else
-			eval "${_Msh_H_func}() {
+			eval "${_Msh_Ho_f}() {
 				${_Msh_H_cmd} || {
 					_Msh_E=\$?
 					${_Msh_H_spp}
 					if let '_Msh_E>128' && _Msh_arg2sig \"\${_Msh_E}\"; then
 						_Msh_P=\"killed by SIG\${_Msh_sig}: \${_Msh_P}\"
 					fi
-					die \"${_Msh_H_func}: command failed with status \${_Msh_E}: \${_Msh_P}\"
+					die \"${_Msh_Ho_f}: command failed with status \${_Msh_E}: \${_Msh_P}\"
 					eval \"unset -v _Msh_P _Msh_E; return \${_Msh_E}\"
 				}
 			}${CCn}"
 		fi
 	else	# Translate the status check expression to an arithmetic expression:
 		# unary operators become binary operators with _Msh_E on the left hand
-		case ${_Msh_H_arg} in
+		case ${_Msh_Ho_e} in
 		( =[!=]* | *[!!\<\>=]=[!=]* | *[%*/+-]=* | *--* | *++* )
-			die "harden: assignment not allowed in status expression: '${_Msh_H_arg}'" || return ;;
+			die "harden: assignment not allowed in status expression: '${_Msh_Ho_e}'" || return ;;
 		( *[=\<\>]* ) ;;
-		( * )	die "harden: unary comparison operator required in status expression: '${_Msh_H_arg}'" || return ;;
+		( * )	die "harden: unary comparison operator required in status expression: '${_Msh_Ho_e}'" || return ;;
 		esac
-		_Msh_H_expr=${_Msh_H_arg}
+		_Msh_H_expr=${_Msh_Ho_e}
 		for _Msh_H_c in '<' '>' '==' '!='; do
 			# use a temporary variable to avoid an infinite loop when
 			# replacing all of one character by one or more of itself
@@ -3378,8 +3399,8 @@ harden() {
 			_Msh_H_expr="(${_Msh_H_expr}) && _Msh_E!=$SIGPIPESTATUS"
 		fi
 		_Msh_E=0
-		( : "$((${_Msh_H_expr}))" ) 2>/dev/null || die "harden: invalid status expression: '${_Msh_H_arg}'" || return
-		let "${_Msh_H_expr}" && { die "harden: success means failure in status expression: ${_Msh_H_arg}" || return; }
+		( : "$((${_Msh_H_expr}))" ) 2>/dev/null || die "harden: invalid status expression: '${_Msh_Ho_e}'" || return
+		let "${_Msh_H_expr}" && { die "harden: success means failure in status expression: ${_Msh_Ho_e}" || return; }
 
 		# Set the hardening function.
 		# (As an exception, there is no '|| return' after 'die', because if we're in
@@ -3387,7 +3408,7 @@ harden() {
 		# its own status code, not that of 'die'.)
 		shellquote _Msh_H_expr
 		if isset _Msh_Ho_t; then
-			eval "${_Msh_H_func}() {
+			eval "${_Msh_Ho_f}() {
 				${_Msh_H_spp}
 				${_Msh_Ho_t}
 				${_Msh_H_cmd} && unset -v _Msh_P || {
@@ -3396,13 +3417,13 @@ harden() {
 						if let '_Msh_E>128' && _Msh_arg2sig \"\${_Msh_E}\"; then
 							_Msh_P=\"killed by SIG\${_Msh_sig}: \${_Msh_P}\"
 						fi
-						die \"${_Msh_H_func}: command failed with status \${_Msh_E}: \${_Msh_P}\"
+						die \"${_Msh_Ho_f}: command failed with status \${_Msh_E}: \${_Msh_P}\"
 					fi
 					eval \"unset -v _Msh_P _Msh_E; return \${_Msh_E}\"
 				}
 			}${CCn}"
 		else
-			eval "${_Msh_H_func}() {
+			eval "${_Msh_Ho_f}() {
 				${_Msh_H_cmd} || {
 					_Msh_E=\$?
 					if let ${_Msh_H_expr}; then
@@ -3410,7 +3431,7 @@ harden() {
 						if let '_Msh_E>128' && _Msh_arg2sig \"\${_Msh_E}\"; then
 							_Msh_P=\"killed by SIG\${_Msh_sig}: \${_Msh_P}\"
 						fi
-						die \"${_Msh_H_func}: command failed with status \${_Msh_E}: \${_Msh_P}\"
+						die \"${_Msh_Ho_f}: command failed with status \${_Msh_E}: \${_Msh_P}\"
 					fi
 					eval \"unset -v _Msh_P _Msh_E; return \${_Msh_E}\"
 				}
@@ -3418,8 +3439,9 @@ harden() {
 		fi
 	fi
 
-	unset -v _Msh_Ho_P _Msh_Ho_t _Msh_Ho_p _Msh_H_cmd _Msh_H_BI _Msh_H_spp _Msh_H_set _Msh_H_unset \
-		_Msh_H_func _Msh_H_isFunc _Msh_H_expr _Msh_H_arg _Msh_E _Msh_H_C || : # BUG_UNSETFAIL compat
+	unset -v _Msh_Ho_e _Msh_Ho_f _Msh_Ho_p _Msh_Ho_t _Msh_Ho_u _Msh_H_V _Msh_H_VA \
+		_Msh_E _Msh_H_BI _Msh_H_C _Msh_H_cmd _Msh_H_expr _Msh_H_isFunc _Msh_H_spp \
+		|| : # BUG_UNSETFAIL compat
 }
 
 # trace: use 'harden' to trace a command with minimal hardening, i.e.: harden only against system errors
