temp files: no more 'set -C', use mkdir/ln instead
The technique to create a uniquely named file with 'set -C' ('set
-o noclobber') and trying output redirection with different names
until it succeeds is not as safe as I thought it was:

- Shell implementations of 'set -C' are not guaranteed to be
  atomic, opening the possibility of race conditions.

- Nothing prevents output redirection under 'set -C' from writing
  into a FIFO or other device file; this can also be used by an
  attacker.

Instead, to create a file, first create a directory with 'mkdir'
(which is safe and atomic), then create the file inside that
subdirectory, and then hardlink it back into the parent directory
with 'ln' (which is also safe and atomic), then remove the
directory.

This method of course has worse performance but should avoid
vulnerabilities. In general, creating temporary directories is best
anyway.

These changes apply to:
- mktemp() in libexec/modernish/sys/base/mktemp.mm
- the bug test in libexec/modernish/cap/BUG_APPENDC.t
- the trap stack implementation of the 'trap' command to print the
  traps, in bin/modernish

Ref.:
https://www.mail-archive.com/austin-group-l@opengroup.org/msg00435.html
https://www.mail-archive.com/austin-group-l@opengroup.org/msg00440.html

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -2769,24 +2769,27 @@ _Msh_POSIXtrap() {
 		# (Sadly, something like _Msh_traps=$(trap) does not work on (d)ash, zsh and mksh/lksh: they do not support the
 		# optional POSIX feature that avoids reseting traps in a subshell if 'trap' is the only command so we can read
 		# traps from a command substitution subshell. We're forced to create a temporary file instead. Be atomic.)
-		_Msh_trapf=$(unset -v F i
+		_Msh_trapd=$(unset -v D i
 			umask 077
-			set -C
-			i=$$
-			until F=/tmp/_Msh_trapf.$i; command : > "$F"; do
-				is -L dir /tmp && can write /tmp || exit
-				i=$((i-1))
-			done 2>/dev/null
-			echo "$F"
-		) || die "trap: can't create temporary file" || return
+			i=0
+			until D=/tmp/_Msh_trapd.$$.$i; command -p mkdir "$D" 2>/dev/null; do
+				case $? in
+				( 126 )	exit 1 "trap: system error: could not invoke 'mkdir'" ;;
+				( 127 ) exit 1 "trap: system error: command not found: 'mkdir'" ;;
+				esac
+				is -L dir /tmp && can write /tmp || exit 1 "trap: system error: /tmp directory not writable"
+				i=$((i+1))
+			done
+			echo "$D"
+		) || die "trap: internal error: can't create temporary directory" || return
 		if thisshellhas BUG_UPP; then
 			command trap ${1+"$@"}
 		else
 			command trap "$@"
-		fi >> "${_Msh_trapf}"
+		fi >> "${_Msh_trapd}/systraps"
 		_Msh_trapE=$?
 		# A little magic to make   var=$(trap)   work on *all* the shells:
-		if let "_Msh_trapE==0" && ! is nonempty "${_Msh_trapf}" && insubshell; then
+		if let "_Msh_trapE==0" && ! is nonempty "${_Msh_trapd}/systraps" && insubshell; then
 			# If the system 'trap' command succeeded, but the temp output file is empty AND we're in a
 			# subshell, this can mean two things: either there are no traps, or the subshell has removed
 			# all traps so we can't print them. But on modernish, we can remedy this by using the fact
@@ -2807,7 +2810,7 @@ _Msh_POSIXtrap() {
 				command trap ${1+"$@"}
 			else
 				command trap "$@"
-			fi >> "${_Msh_trapf}"
+			fi >> "${_Msh_trapd}/systraps"
 			_Msh_trapE=$?
 			# Unset the dummy traps.
 			eval "command trap - ${_Msh_sigs2cleanup}"
@@ -2819,15 +2822,15 @@ _Msh_POSIXtrap() {
 		# function, which can easily parse the arguments and print both the stack traps and the POSIX traps.
 		if let "_Msh_trapE==0"; then
 			alias trap='_Msh_printSysTrap'
-			command . "${_Msh_trapf}" || die "trap: internal error" || return
+			command . "${_Msh_trapd}/systraps" || die "trap: internal error" || return
 			alias trap='_Msh_POSIXtrap'
 		fi
 		# Cleanup.
 		case $- in
-		( *m* )	command -p rm -f "${_Msh_trapf}" ;;
-		( * )	command -p rm -f "${_Msh_trapf}" & ;;
+		( *m* )	command -p rm -rf "${_Msh_trapd}" ;;
+		( * )	command -p rm -rf "${_Msh_trapd}" & ;;
 		esac
-		eval "unset -v _Msh_trapf _Msh_trapE; return ${_Msh_trapE}" ;;
+		eval "unset -v _Msh_trapd _Msh_trapE; return ${_Msh_trapE}" ;;
 	( 1,-[!-]* | 1,--?* )
 		# allow system-specific things such as "trap -l" (bash) or "trap --help" (ksh93, yash)
 		command trap "$@"
