Fix "harden -p" for ksh93 and yash
bin/modernish:
- harden(): fix "harden -p":
  . remove ugly SIGPIPE exit status test
  . use a better method for finding the exit status corresponding to SIGPIPE
  Result: 'harden -p' now works on all POSIX shells, including ksh93 and yash.
- POSIX trap emulation command: fix passing on system-specific options
- new system constants: MSH_SHELL, MSH_PREFIX (default shell upon
  installation, and installation prefix)
- more robust way of finding modules dir: use prefix given by install.sh

install.sh:
- hardcode path to default shell and installation prefix into installed bin/modernish
- check for paths containing non-shell-safe characters

uninstall.sh:
- add BUG_ALSUBSH workaround

share/doc/modernish/WRITEUP.md:
- minor typographical fix

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1,4 +1,6 @@
 #! /bin/sh
+MSH_SHELL=/bin/sh	# this line and the next will be changed by install.sh
+MSH_PREFIX=${srcdir:-$PWD}
 # -*- mode: sh; -*-
 
 # modernish - an attempt at a cross-platform POSIX shell modernizer library.
@@ -25,6 +27,8 @@
 # modernish system constants (read-only variables):
 #	$MSH_VERSION		version of modernish
 #	$MSH_CAP		space-separated ID list of shell capabilities and bugs
+#	$MSH_SHELL		default shell for this modernish installation (e.g. /bin/sh)
+#	$MSH_PREFIX		installation prefix for this modernish installation (e.g. /usr/local)
 #	$ME			replacement for $0 (for hashbang path #!/usr/bin/env modernish)
 #	$UID			the invoking user's UID
 #	$USER			the invoking user's username
@@ -54,8 +58,14 @@
 
 case ${MSH_VERSION+s} in
 ( s )	if ! { (unset -v MSH_VERSION) 2>/dev/null && unset -v MSH_VERSION; }; then
-		echo "modernish is already initialized." 1>&2
-		return 1 || exit 1
+		case ${1:-} in
+		( --version )
+			printf '%s\n' "$MSH_VERSION"
+			return 0 ;;
+		( * )
+			printf '%s\n' 'Modernish is already initialized. To reload it, exit this shell first.' 1>&2
+			return 1 || exit 1 ;;
+		esac
 	fi ;;
 esac
 
@@ -135,27 +145,6 @@ export POSIXLY_CORRECT=y	# this also sets -o posix on bash
 # -------------
 
 # Initialization, phase 1.
-
-# As we're setting stuff to read-only, guard against initializing twice.
-# (zsh has BUG_CMDSPCIAL, so it exits the shell upon trying to unset a read-
-# only, even when using 'command' to disable the 'unset' commands specialness;
-# therefore, don't suppress an error message from 'unset' with 2>|/dev/null,
-# because it's the only thing zsh users will get to see. This could be fixed
-# by forking a subshell just for this test, but it's not worth it.)
-command unset -v MSH_VERSION
-case ${MSH_VERSION+s} in
-( s )
-	case ${1:-} in
-	( --version )
-		printf '%s\n' "$MSH_VERSION"
-		return 0
-		;;
-	( * )
-		printf '%s\n' 'Modernish is already initialized. To reload it, exit this shell first.' 1>&2
-		return 1
-		;;
-	esac ;;
-esac
 
 # Modernish does _not_ support -e (-o errexit); for many commands, we need to
 # be able to distinguish between "false" (1) and "error" (2 or greater) exit
@@ -248,6 +237,7 @@ _Msh_have() {
 # FTL_ROASSIGN: unpatched pdksh
 readonly MSH_VERSION=0.04dev 2>| /dev/null
 test "${MSH_VERSION:-}" = 0.04dev || _Msh_have FTL_ROASSIGN "'readonly' command doesn't support assignment."
+readonly MSH_SHELL MSH_PREFIX || _Msh_have FTL_ROSERIES "'readonly' can't make a series of variables read-only."
 
 # For the next four tests, disable $PATH to avoid finding spurious
 # external versions of 'alias', 'unalias' and 'command' (*BSD, Mac)
@@ -1327,7 +1317,7 @@ use() {
 	# return gracefully if the module was already loaded
 	isset "${_Msh_use_V}" && return
 
-	[ -r "$_Msh_ModulesDir/$_Msh_use_M.mm" ] || die "use: module ${_Msh_use_M} not found" || return
+	[ -r "$MSH_PREFIX/libexec/modernish/${_Msh_use_M}.mm" ] || die "use: module ${_Msh_use_M} not found" || return
 
 	case $# in
 	( 0 )	_Msh_doUse ;;	# BUG_UPP workaround, BUG_PARONEARG compatible
@@ -1351,7 +1341,7 @@ use() {
 # script" without saying whether the deepest item in the call hierarchy
 # should take priority or not.)
 _Msh_doUse() {
-	. "${_Msh_ModulesDir}/${_Msh_use_M}.mm"
+	. "$MSH_PREFIX/libexec/modernish/${_Msh_use_M}.mm"
 }
 
 # -------------
@@ -2613,26 +2603,32 @@ clearstack() {
 
 # Convert an argument in ${_Msh_sig} to a signal name, minus the SIG- prefix, and check for validity.
 # Internal function. Subject to change without notice.
-# TODO? convert lower case to upper case
-# TODO: figure out how to handle system-specific traps
 _Msh_arg2sig() {
 	case ${1:+n} in
 	( n )	_Msh_sig=$1 ;;
 	esac
 	case ${_Msh_sig} in
-	( 0 )	_Msh_sig='EXIT' ;;
-	( 1 )	_Msh_sig='HUP' ;;
-	( 2 )	_Msh_sig='INT' ;;
-	( 3 )	_Msh_sig='QUIT' ;;
-	( 6 )	_Msh_sig='ABRT' ;;
-	( 9 )	_Msh_sig='KILL' ;;
-	( 14 )	_Msh_sig='ALRM' ;;
-	( 15 )	_Msh_sig='TERM' ;;
-	( * )	_Msh_sig=${_Msh_sig#SIG}
+	( 0 )	_Msh_sig='EXIT' ;;	# this is not really a signal
+	( 1 )	_Msh_sig='HUP' ;;	# \
+	( 2 )	_Msh_sig='INT' ;;	# |
+	( 3 )	_Msh_sig='QUIT' ;;	#  \
+	( 6 )	_Msh_sig='ABRT' ;;	#   } these are guaranteed by POSIX
+	( 9 )	_Msh_sig='KILL' ;;	#  /
+	( 14 )	_Msh_sig='ALRM' ;;	# |
+	( 15 )	_Msh_sig='TERM' ;;	# /
+	( *[!0123456789]* )
+		# signal name: make upper case, remove SIG, check validity
+		case ${_Msh_sig} in
+		( *[a-z]* )
+			_Msh_sig=$(command -p printf '%s\n' "${_Msh_sig}" | command -p tr a-z A-Z) ;;
+		esac
+		_Msh_sig=${_Msh_sig#SIG}
 		case ${_Msh_sig} in
 		( '' | [0123456789]* | *[!ABCDEFGHIJKLMNOPQRSTUVWXYZ01213456789]* )
 			return 1 ;;
 		esac ;;
+	( * )	# other signal number: ask 'kill' for a name
+		_Msh_sig=$(kill -l "${_Msh_sig}" 2>/dev/null) ;;
 	esac
 }
 
@@ -2731,7 +2727,7 @@ _Msh_doTraps() {
 alias trap='_Msh_POSIXtrap'
 _Msh_POSIXtrap() {
 	case ${#},${1-} in
-	( 0, | 1,-- | 1,-p | 1,--print )
+	( 0, | 1,-- | *,-p | *,--print )
 		# Print the traps, both legacy and stack.
 		# (Sadly, something like _Msh_traps=$(trap) does not work on (d)ash, zsh and mksh/lksh: contrary to
 		# POSIX, they reset traps in a subshell even if 'trap' is the only command, so we can't read traps
@@ -2746,7 +2742,12 @@ _Msh_POSIXtrap() {
 			done 2>/dev/null
 			echo "$F"
 		) || die "trap: can't create temporary file" || return
-		command trap >> "${_Msh_trapf}" || die "trap: can't write to temporary file" || return
+		if thisshellhas BUG_UPP; then
+			command trap ${1+"$@"}
+		else
+			command trap "$@"
+		fi >> "${_Msh_trapf}"
+		_Msh_trap_e=$?
 		_Msh_trapC=''
 		while IFS= read -r _Msh_trapL; do
 			_Msh_trapC=${_Msh_trapC:+$_Msh_trapC$CCn}${_Msh_trapL}
@@ -2755,6 +2756,11 @@ _Msh_POSIXtrap() {
 		( *i* )	rm -f "${_Msh_trapf}" ;;
 		( * )	rm -f "${_Msh_trapf}" & ;;
 		esac
+		case ${_Msh_trap_e} in
+		( [!0]* )
+			die "trap: system 'trap' command failed" || return ;;
+		esac
+		unset -v _Msh_trap_e
 		# We need to list lists all the traps in the form of shell-quoted commands that are suitable for execution
 		# by the shell. It is possible for the third argument (the command to execute) to span multiple lines, so
 		# just eval-ing them line by line won't work reliably. A more robust method is to alias 'trap' to a shell
@@ -2919,35 +2925,7 @@ fi
 # or any command with a name that would be invalid for a shell
 # function, you have harden it 'as' a different name.
 #
-# *** SIGPIPE handling: ***
-# To do sensible hardening, we need to be able to whitelist for processes
-# killed by SIGPIPE, so that things like 'gzip -dc textfile.txt | head -n
-# 10' don't kill the program if gzip is killed by SIGPIPE. According to
-# POSIX, the numerical value of SIGPIPE, and therefor its exit status, is
-# implementation-defined. I don't know of any real-world system where it
-# isn't 13 (and therefore the corresponding exit status is 128+13=141), but
-# just to be sure, try to find the PIPE signal's value on this system.
-while IFS= read -r _Msh_n && IFS= read -r _Msh_S; do
-	case ${_Msh_S} in
-	( [pP][iI][pP][eE] )
-		break ;;
-	esac
-done <<EOF
-$(for sig in 13 4 5 7 8 10 11 12 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
-	echo "$sig"
-	kill -l "$sig"
-done)
-EOF
-case ${_Msh_S} in
-( [pP][iI][pP][eE] )
-	;;
-( * )
-	echo "modernish: Fatal: cam't locate signal number of SIGPIPE" 1>&2
-	return 2 || exit 2 ;;
-esac
-_Msh_PIPEstatus=$((_Msh_n+128))
-readonly _Msh_PIPEstatus
-unset -v _Msh_n _Msh_S
+unset -v _Msh_PIPEstatus
 harden() {
 	unset -v _Msh_Ho_p
 	while :; do
@@ -2978,6 +2956,7 @@ harden() {
 	( '' | [0123456789]* | *[!${ASCIIALNUM}_]* )
 		die "harden: invalid shell function name: ${_Msh_H_func}" || return
 		;;
+	# TODO: create a proper check for a shell reserved word
 	( 'command' | 'set' | 'return' | 'case' | 'do' | 'done' | 'elif' | 'else' \
 	| 'esac' | 'fi' | 'for' | 'if' | 'in' | 'then' | 'until' | 'while' )
 		die "harden: can't harden '${_Msh_H_func}'" || return
@@ -3011,7 +2990,7 @@ harden() {
 		esac &&
 		! isset _Msh_Ho_p
 	then
-		# For efficiency, handle a simple non-zero check specialy.
+		# For efficiency, handle a simple non-zero check specially.
 		eval "${_Msh_H_func}() {
 			${_Msh_H_cmd} || {
 				_Msh_E=\$?
@@ -3043,6 +3022,26 @@ harden() {
 		done
 		unset -v _Msh_H_nwex _Msh_H_c
 		if isset _Msh_Ho_p; then
+			# We need to be able to whitelist the exit status of processes killed by SIGPIPE,
+			# so that things like 'gzip -dc textfile.txt | head' don't kill the program if a
+			# hardened 'gzip' is killed by SIGPIPE. Hence the -p option.
+			# According to POSIX, the numerical value of SIGPIPE is implementation-defined. In
+			# addition, different shells have different exit status offsets for signals: ksh93
+			# has signum+256, the rest signum+128. So we have to kill a process with SIGPIPE to
+			# find out its exit status. Do this the first time the value is needed.
+			if not isset _Msh_PIPEstatus; then
+				case $- in
+				( *i* )	"$MSH_SHELL" -c 'kill -s PIPE $$' ;;
+				( * )	# Credit to jt@toerring.de (Jens Thoms Toerring) for the fast method to find the exit
+					# status. comp.unix.shell Message-ID: <diuks5Fbik0U1@mid.uni-berlin.de>
+					# Use it for non-interactive shells only to avoid job control clutter on the terminal.
+					(while :; do command -p sleep 1; done) &
+					kill -s PIPE "$!"
+					wait "$!" ;;
+				esac
+				_Msh_PIPEstatus=$?
+				readonly _Msh_PIPEstatus
+			fi
 			_Msh_H_expr="(${_Msh_H_expr}) && _Msh_E!=${_Msh_PIPEstatus}"
 		fi
 		_Msh_E=0
@@ -4010,20 +4009,6 @@ fi
 
 # Initialization, phase 2.
 
-
-# Temporary identity.
-# TODO: make this robust using the installer.
-if endswith "$0" '/modernish'; then
-	ME=$0
-else
-	ME=$(command -v modernish) || _Msh_doExit 127 "modernish: can't find myself; please add my dir to PATH"
-fi
-
-# Find the directory of modernish modules
-_Msh_ModulesDir=${ME%/*/*}/libexec/modernish
-[ -d "${_Msh_ModulesDir}" ] || _Msh_doExit 127 "modernish: modules directory '${_Msh_ModulesDir}' not found"
-readonly _Msh_ModulesDir
-
 # Restore 'allexport' option if it was set
 if isset _Msh_allexport; then
 	set -a
@@ -4035,6 +4020,7 @@ fi
 # --------------------
 
 # Find out how modernish was invoked and launch the invoking program if necessary.
+ME=$0	# temporary identity for possible error messages
 if ! endswith "$0" '/modernish'; then
 	# modernish was sourced
 	case $- in
