insubshell() bugfix, broken /bin/sh workaround
The default version of insubshell() depends on being able to exec a shell that
is capable of reporting $PPID back to it. Some of the rest of modernish, such
as die(), depends on insubshell() working. However, just using /bin/sh does not
always work: although it's been mandated by POSIX for a long time, some /bin/sh
still don't support $PPID in 2016 (I'm looking at you, NetBSD).

bin/modernish:
- Fix infinite loop between insubshell() and die() in the event the shell
  remembered in $MSH_SHELL does not support $PPID.

install.sh, uninstall.sh:
- Before initialising modernish, make sure $MSH_SHELL is a shell supporting
  $PPID; look for one if necessary.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1532,7 +1532,10 @@ else	# Default, slow version. We must exec a shell to get it to report our PID b
 		esac
 		case $(exec "$MSH_SHELL" -c 'echo $PPID') in
 		( "$$" ) return 1 ;;
-		( '' )	die "insubshell: internal error: $MSH_SHELL does not have \$PPID! Reinstall modernish." ;;
+		( '' )	# can't call die() here because it uses insubshell(): infinite loop
+			echo "insubshell: internal error: $MSH_SHELL does not have \$PPID! Reinstall modernish." 1>&2
+			isset -i && kill -s INT "$$" || { command trap - TERM; kill -s TERM "$$"; }
+			command exit 125 ;;
 		esac
 	}
 fi
