harden() bugfix: properly avoid trying to harden an alias
bin/modernish:
  - On the one hand,
	$ alias sudo='sudo '
	$ harden -p -t -f chown sudo chown
	modernish on bash: harden: aliases are not supported: alias sudo='sudo '
    If the hardening function name is not itself an alias, this shouldn't
    be a problem; the function should use 'command' to bypass the alias.
    This is now allowed.
  - On the other hand,
	$ alias foo=bar
	$ harden -f foo ls
    would set a function called 'bar' instea of one called 'foo'.
    This is now blocked.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3204,8 +3204,11 @@ harden() {
 		die "${_Msh_H_C-harden}: invalid shell function name: ${_Msh_H_func}" || return
 		;;
 	esac
-	isvarname "${_Msh_H_func}" && thisshellhas "--rw=${_Msh_H_func}" &&
-		{ die "${_Msh_H_C-harden}: can't harden reserved word '${_Msh_H_func}'" || return; }
+	if isvarname "${_Msh_H_func}" && thisshellhas "--rw=${_Msh_H_func}"; then
+		die "${_Msh_H_C-harden}: can't harden reserved word '${_Msh_H_func}'" || return
+	elif alias "${_Msh_H_func}" >/dev/null 2>&1; then
+		die "harden: function name '${_Msh_H_func}' conflicts with alias '${_Msh_H_func}'" || return
+	fi
 
 	# check if setting a function is possible
 	(eval "${_Msh_H_func}() { :; }") 2>/dev/null || die "${_Msh_H_C-harden}: can't harden '${_Msh_H_func}'" || return
