'trap': bugfix: reset signals if first argument is decimal number
bin/modernish:
- _Msh_POSIXtrap(): POSIX compliance fix. Properly detect if the
  first operand is an unsigned decimal integer, in which case we
  need to interpret all operands as signals to unset. This fixes a
  bug where '0' was not recognised as EXIT to unset. It now also
  considers a big positive integer number in the first operand as a
  signal (which is then found invalid). This behaviour is what
  POSIX prescribes, though it differs from most shells.
  Ref.: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_28

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3291,8 +3291,14 @@ _Msh_POSIXtrap() {
 	( -- )	shift ;;
 	esac
 
+	case ${1-} in
+	( '' | *[!0123456789]* ) ;;
+	( * )	# First operand is unsigned integer: reset signals.
+		set -- - "$@" ;;
+	esac
+
 	case ${#},$1 in
-	( 1,* | *,- | *,[1-9] | *,[1-9][0-9] )
+	( 1,* | *,- )
 		# Emulation of system command to unset a trap.
 		case ${#},$1 in
 		( 1,- )	die 'trap (unset): signal specification expected' || return ;;
@@ -3306,7 +3312,7 @@ _Msh_POSIXtrap() {
 				fi
 				unset -v "_Msh_POSIXtrap${_Msh_sigv}" _Msh_sig _Msh_sigv
 			else
-				die "trap (unset): invalid signal name: '${_Msh_sig}'" || return
+				die "trap (unset): invalid signal: '${_Msh_sig}'" || return
 			fi
 		done ;;
 	( * )	# Emulation of system command to set a trap.
@@ -3324,7 +3330,7 @@ _Msh_POSIXtrap() {
 				fi
 				eval "_Msh_POSIXtrap${_Msh_sigv}=\${_Msh_trap_CMD}"
 			else
-				die "trap (set): invalid signal name: '${_Msh_sig}'" || return
+				die "trap (set): invalid signal: '${_Msh_sig}'" || return
 			fi
 		done
 		unset -v _Msh_trap_CMD _Msh_sig _Msh_sigv ;;
