BUG_CMDPV fix and related tweaks to harden() and installer
libexec/modernish/cap/BUG_CMDPV.t:
- detect a variant of BUG_CMDPV on bash 3.2: the '-p' option is
  ignored altogether in 'command -pv', so the default system PATH
  is not used as expected.

README.md:
- update BUG_CMDPV documentation.

bin/modernish:
- harden(): option -p:
  No longer use 'command -pv' at all to determine the default
  system path to a command; it is broken on too many shells/OSs.
  Instead, always use the output of 'getconf PATH'.

install.sh, uninstall.sh:
- use 'harden -p' to harden standard POSIX utilities, ensuring that
  a valid POSIX version is used. This means the installer now works
  on an untweaked Solaris, where the default $PATH leads to ancient
  pre-POSIX Unix utilities.
  In install.sh, trace 'mkdir' with -t instead of manually printing
  messages on creating directories.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3110,20 +3110,17 @@ harden() {
 
 	isset _Msh_H_func || _Msh_H_func=$1
 	if isset _Msh_Ho_p; then
-		if thisshellhas BUG_CMDPV; then
-			# We cannot use 'command -pv', so temporarily set PATH to system default
-			push PATH
-			PATH=${_Msh_defPATH:=$(command -p getconf PATH 2>/dev/null ||
-						command -p echo /bin:/usr/bin:/sbin:/usr/sbin)}
-			_Msh_H_cmd=$(command -v -- "$1") && pop PATH || { pop PATH; ! :; }
-		else
-			_Msh_H_cmd=$(command -pv -- "$1")
-		fi
+		push PATH
+		PATH=${_Msh_defPATH:=$(command -p getconf PATH 2>/dev/null ||
+					command -p echo /bin:/usr/bin:/sbin:/usr/sbin)}
+		_Msh_H_cmd=$(command -v -- "$1")
+		pop PATH
 	else
 		_Msh_H_cmd=$(command -v -- "$1")
-	fi || die "${_Msh_H_C-harden}${_Msh_Ho_p+ -p}: command not found: '$1'" || return
+	fi
 
 	case ${_Msh_H_cmd} in
+	( '' )	die "${_Msh_H_C-harden}${_Msh_Ho_p+ -p}: command not found: '$1'" || return ;;
 	( 'alias '* )
 		# Hardening aliases is too risky. It basically amounts to using 'eval' with untrusted
 		# and unvalidated input. Aliases could contain any combination of shell grammar and
