2015-04-15
modified:   bin/modernish
- new: exitwith [ -u ] [ <status> [ <message> ] ]
- so() and not() to check for success or failure

modified:   libexec/modernish/catchfail
- check if module is already loaded

modified:   libexec/modernish/getlongopts
- first attempt at overloading the 'getopts' builtin with a long options option

new file:   libexec/modernish/testsuite/catchfail-test
- simple test for catchfail

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/zsh
 # modernish - a shell moderniser library that targets POSIX plus local variables.
 # POSIX reference: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/contents.html
 
@@ -14,7 +14,7 @@
 # - trawl for functionality: http://www.etalabs.net/sh_tricks.html
 
 
-# Safe and portable 'echo' (for control chars, use printf instead)
+# Safe and portable 'echo' (if you want control chars, use printf instead)
 echo() {
 	if test "$1" = '-n'; then
 		shift
@@ -24,52 +24,74 @@ echo() {
 	fi
 }
 
-# Exit gracefully on error. Usage: die [ -u ] <exitstatus> [ <message> ]
-#	(No local variables here because this is also used for the error
-#	about missing local variables support.)
-die() {
+# Extended 'exit'. Usage: exitwith [ -u ] [ <status> [ <message> ] ]
+# (We cannot overload 'exit' itself. ksh says: invalid function name)
+exitwith() {
+	exitstatus=$?
 	unset -v opt_usage
 	test "$1" = "-u" && opt_usage=y && shift
 	exitstatus=$1
 	shift
 	test -n "$*" && printf '%s: %s\n' "${ME##*/}" "$*" 1>&2
 	test -n "$opt_usage" && printf 'Type %s --help for help.\n' "${ME##*/}" 1>&2
-	mypid=$(exec sh -c 'printf "%u\n" $PPID') || exit $exitstatus
-	test $mypid -ne $$ && kill $$  # error out even from subshells
 	exit $exitstatus
+}
+
+# Exit gracefully on error, even from subshells. Usage: die [ -u ] [ <message> ]
+die() {
+	unset -v opt_usage
+	test "$1" = "-u" && opt_usage=y && shift
+	test -n "$*" && printf '%s: %s\n' "${ME##*/}" "$*" 1>&2
+	test -n "$opt_usage" && printf 'Type %s --help for help.\n' "${ME##*/}" 1>&2
+	mypid=$(exec sh -c 'printf "%u\n" $PPID') || exit $exitstatus
+	test $mypid -ne $$ && kill $$  # if we're in a subshell, kill main process
+	exit 143   # same exit status as produced by kill, for consistency
 }
 
 # Use a modernish module.
 use() {
-	test $# -gt 0 || die 255 "use: needs module name"
-	test -r "${_msh_ModulesDir}/$1" || die 255 "use: module $1 not found"
+	test $# -gt 0 || die "use: needs module name"
+	test -r "${_msh_ModulesDir}/$1" || die "use: module $1 not found"
 	. "${_msh_ModulesDir}/$1" "$@"
 }
 
+# Check for success. Allows: if so; then <commands>; fi
+so() {
+	test $? -eq 0
+}
+
+# Check for non-success. Allows: if not; then <commands>; fi
+not() {
+	test $? -ne 0
+}
 
 # --- init ---
 
 # Get the GNU to behave a little better.
 export POSIXLY_CORRECT=y
 
-# Temporary identity.
-ME=$(command -v modernish) || die 255 "can't find myself"
+# Beat zsh into compliance.
+test -z "$ZSH_VERSION" || emulate sh
 
-# Test if this shell supports local variables.
-testlocal() { local testvar=1 && test $testvar -eq 1 || die 255 "requires local variables support"; }
-testlocal
-unset -f testlocal
+# Temporary identity.
+ME=$(command -v modernish) || ME=modernish die "can't find myself"
+
+# Test if this shell supports local variables. If not, provide a fake substitute.
+# (As far as I know, this is only ksh93.)
+testlocal() { local testvar=1 && test $testvar -eq 1; }
+testlocal 2>/dev/null || die "this shell does not support local variables"
 
 # Find the modules directory.
 dir="${ME%/*}/../libexec/modernish"
-readonly _msh_ModulesDir=$(cd "$dir" && pwd -P) || die 255 "modules directory not found"
+readonly _msh_ModulesDir=$(cd "$dir" && pwd -P) || die "modules directory not found"
 unset -v dir
 
 # Find out how modernish was invoked and run the invoking program.
 if test "${0##*/}" = 'modernish' && test $# -gt 0; then
 	# modernish has been loaded with '#!/usr/bin/env modernish'
 	readonly ME="$1"
-	. "$@"
+	shift
+	. "$ME" "$@"
 else
 	# modernish has been sourced
 	readonly ME="$0"
diff --git a/libexec/modernish/catchfail b/libexec/modernish/catchfail
--- a/libexec/modernish/catchfail
+++ b/libexec/modernish/catchfail
@@ -1,4 +1,5 @@
 #! /bin/sh
+if test -z "${_msh_using_catchfail}"; then
 
 catchfail() {
 	local statustest="$1"  # some ash/dash need quotes here to not b0rk on variable name within variable
@@ -7,6 +8,9 @@ catchfail() {
 	command "$@"
 	local status=$?
 	#set -e		# TODO: how to save set {-,+}e state?
-	eval "$statustest" || die $status "failed \"$statustest\" with status $status: $@"
+	eval "$statustest" || die "failed \"$statustest\" with status $status: $@"
 	return $status
 }
+
+_msh_using_catchfail=y
+fi
