Detect here-strings cap. & new bugs; various tweaks; version 0.2.1
libexec/modernish/cap/HERESTR.t:
- new feature test: here strings

libexec/modernish/cap/BUG_SELECT{EOF,RPL}.t:
- detect two bugs in 'select' on mksh and zsh, respectively

bin/modernish:
- move init of $UID and $USER to an optional module (sys/user/id)
- properly abort initialisation on failure (use a function)
- ematch(): more efficient grepping with here-string (if available)
  or here-document instead of a piping from 'echo'
- complete missing documentation of is() in the comments
- various minor tweaks
- version bump to 0.2.1

libexec/modernish/sys/user/id.mm:
- new module for $UID and $USER

libexec/modernish/sys/user/loginshell.mm:
- renamed from libexec/modernish/sys/userinfo.mm

libexec/modernish/loop/select.mm:
- implement detection and workaround declaration mechanism for BUG_SELECTRPL
  and BUG_SELECTEOF

install.sh:
- edits to reflect the above changes
- cope with BUG_SELECTRPL (found on older mksh)

share/doc/modernish/WRITEUP.md:
- updates to reflect the above changes

share/doc/modernish/Makefile:
- use 'markdown' instead of 'multimarkdown' by default

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -27,8 +27,6 @@
 #	$MSH_SHELL		default shell for this modernish installation (e.g. /bin/sh)
 #	$MSH_PREFIX		installation prefix for this modernish installation (e.g. /usr/local)
 #	$ME			replacement for $0 (for hashbang path #!/usr/bin/env modernish)
-#	$UID			the invoking user's UID
-#	$USER			the invoking user's username
 #	$CC?			control characters $CCn, etc. (same as printf \n, etc.)
 #	$CC??			control characters $CC01 .. $CC1F
 #	$CONTROLCHARS		all control characters
@@ -40,15 +38,28 @@
 
 # -------------
 
+# Internal function for aborting initialisation.
+# Usage: _Msh_initExit 1 "error message" || return
+_Msh_initExit() {
+	_Msh_E=$1
+	shift
+	if [ -e ~/.modernish-force ]; then
+		printf 'modernish: %s\n' "$@" "Continuing anyway. THINGS WILL BREAK." 1>&2
+		return 0
+	fi
+	printf 'modernish: %s\n' "$@" "Initialisation failed. Aborting." 1>&2
+	case $- in
+	( *i* )	return "${_Msh_E}" ;;	# try not to exit an interactive shell
+	( * )	exit "${_Msh_E}" ;;
+	esac
+}
+
 case ${MSH_VERSION+s} in
 ( s )	if ! { (unset -v MSH_VERSION) 2>|/dev/null && unset -v MSH_VERSION; }; then
 		case ${1:-} in
 		( --version )
-			printf '%s\n' "$MSH_VERSION"
-			return 0 ;;
-		( * )
-			printf '%s\n' 'Modernish is already initialized. To reload it, exit this shell first.' 1>&2
-			return 1 || exit 1 ;;
+			_Msh_initExit 0 "$MSH_VERSION" || return ;;
+		( * )	_Msh_initExit 1 'Already initialised. To reload modernish, exit this shell first.' || return;;
 		esac
 	fi ;;
 esac
@@ -179,16 +190,6 @@ case $- in
 ( * )	unset -v _Msh_allexport ;;
 esac
 
-# Bash has the read-only variable $UID, as well as $USER which is not
-# read-only. Give them to other shells too, and make both of them read-only.
-case ${UID+s} in
-( '' )	UID=$(command -p id -u) || exit 127 ;;
-esac
-case ${USER+s} in
-( '' )	USER=$(command -p id -un) || exit 127 ;;
-esac
-readonly UID USER
-
 # --- Built-in shell feature, quirk, bug and POSIX compliance requirement checks ---
 # Block on fatal shell bugs and standards incompatibilities that would break
 # modernish. Identify quirks and nonstandard features. As a side effect,
@@ -221,8 +222,7 @@ _Msh_testFn() {
 		case $# in
 		( 1 )	;;		# no field splitting: it is empty and set
 		( 3 )	false ;;	# default field splitting: it is unset
-		( * )	echo "modernish: Internal error with field splitting! Aborting." 1>&2
-			exit 3 ;;
+		( * )	_Msh_initExit 3 "Internal error with field splitting!" || return ;;
 		esac ;;
 	esac
 }
@@ -243,9 +243,9 @@ _Msh_have() {
 
 # The version and location of modernish.
 # FTL_ROASSIGN: unpatched pdksh
-readonly MSH_VERSION=0.2.0dev 2>| /dev/null
+readonly MSH_VERSION=0.2.1dev 2>| /dev/null
 case ${MSH_VERSION:-} in
-( 0.2.0dev ) ;;
+( 0.2.1dev ) ;;
 ( * ) _Msh_have FTL_ROASSIGN "'readonly' command doesn't support assignment." ;;
 esac
 MSH_SHELL=${MSH_SHELL:-/bin/sh}	# this line and the next will be changed by install.sh
@@ -756,16 +756,8 @@ esac 2>|/dev/null
 # --- End of builtin tests ---
 case ${_Msh_ftlcount} in
 ( 0 )	;;
-( * )	case ${_Msh_ftlcount} in
-	( 1 )	printf '1 fatal bug found. ' ;;
-	( * )	printf '%d fatal bugs found. ' "${_Msh_ftlcount}" ;;
-	esac 1>&2
-	if [ -e ~/.modernish-force ]; then
-		printf 'Proceeding anyway. THINGS WILL BREAK.\n'
-	else
-		printf "Sorry, this shell can't run modernish.\n"
-		exit 127
-	fi 1>&2 ;;
+( 1 )	_Msh_initExit 3 "1 fatal shell bug found. This shell can't run modernish." || return ;;
+( * )	_Msh_initExit 3 "${_Msh_ftlcount} fatal shell bugs found. This shell can't run modernish." || return ;;
 esac
 case ${_Msh_IFS+s} in
 ( s )	IFS=${_Msh_IFS}; unset -v _Msh_IFS ;;
@@ -809,7 +801,7 @@ CC0A='
 IFS=',' read CC01 CC02 CC03 CC04 CC05 CC06 CC07 \
 	CC08 CC09      CC0B CC0C CC0D CC0E CC0F \
 	CC10 CC11 CC12 CC13 CC14 CC15 CC16 CC17 \
-	CC18 CC19 CC1A CC1B CC1C CC1D CC1E CC1F <<endofCC || exit 127
+	CC18 CC19 CC1A CC1B CC1C CC1D CC1E CC1F <<endofCC || _Msh_initExit 3 "CC* character constants: 'read' failed" || return
 $(command -p printf '\1,\2,\3,\4,\5,\6,\7,\10,\11,\13,\14,\15,\16,\17,\20,\21,\22,\23,\24,\25,\26,\27,\30,\31,\32,\33,\34,\35,\36,\37')
 endofCC
 ;;
@@ -1268,7 +1260,7 @@ eval "thisshellhas() {
 		( 0 )	break ;;
 		esac
 	done
-}${CCn}" || exit
+}${CCn}" || _Msh_initExit 3 "thisshellhas() definition: 'eval' failed" || return
 unset -v _Msh_tSH_testBI _Msh_tSH_testKW _Msh_tSH_bashLEPIPEMAIN
 
 # builtin: Run a shell built-in command. Most shells come with 'builtin'
@@ -1415,9 +1407,8 @@ if thisshellhas --rw=[[; then
 	else
 		# version for [[ without -v
 		if thisshellhas BUG_IFSISSET; then
-			printf '%s\n' "You're on a shell with BUG_IFSISSET but without '[[ -v'!" \
-				"This is not known to exist, so workaround not implemented. Please report." 1>&2
-			exit 127
+			_Msh_initExit 3 "You're on a shell with BUG_IFSISSET but without '[[ -v'!" \
+				"This is not known to exist, so workaround not implemented. Please report." || return
 		fi
 		isset() {
 			case ${#},${1-} in
@@ -1433,9 +1424,8 @@ if thisshellhas --rw=[[; then
 	fi
 else
 	if thisshellhas BUG_IFSISSET; then
-		printf '%s\n' "You're on a shell with BUG_IFSISSET but without '[['!" \
-			"This is not known to exist, so workaround not implemented. Please report." 1>&2
-		exit 127
+		_Msh_initExit 3 "You're on a shell with BUG_IFSISSET but without '[['!" \
+			"This is not known to exist, so workaround not implemented. Please report." || return
 	fi
 	# default (POSIX) version
 	isset() {
@@ -2668,7 +2658,7 @@ harden() {
 	# determine status checking method and set hardening function
 	_Msh_H_arg=${2:-'>0'}
 	if	case ${_Msh_H_arg} in
-		( '>0' | '> 0' | '>=1' | '>= 1' ) ;;
+		( '>0' | '> 0' | '>=1' | '>= 1' | '!=0' | '!= 0' ) ;;
 		( * ) false ;;
 		esac &&
 		! isset _Msh_Ho_p
@@ -2866,9 +2856,8 @@ else
 		}'
 	else
 		if thisshellhas BUG_IFSISSET; then
-			printf '%s\n' "modernish: Fatal error: You're on a shell with BUG_IFSISSET that is not ksh93!" \
-				"This is not known to exist; please report. Aborting." 1>&2
-			exit 127
+			_Msh_initExit 3 "You're on a shell with BUG_IFSISSET that is not ksh93!" \
+				"This is not known to exist; please report." || return
 		fi
 		# default (POSIX, no local variables)
 		echo() {
@@ -3146,9 +3135,8 @@ identic() {
 #	safe'.)
 #
 # ...	If we're running on bash, ksh or zsh:
-if PATH=/dev/null; eval "[[ 'a${CCn}b' < 'a${CCn}bb' && 'a${CCn}bb' > 'a${CCn}b' ]]"
+if thisshellhas --rw=[[ && eval "[[ 'a${CCn}b' < 'a${CCn}bb' && 'a${CCn}bb' > 'a${CCn}b' ]]"
 then
-	PATH=${_Msh_PATH}
 	sortsbefore() {
 		case $# in
 		( 2 )	[[ $1 < $2 ]] ;;
@@ -3164,9 +3152,8 @@ then
 # ...	Try to fall back to builtin '['/'test' non-standard feature.
 #	Thankfully, '<' and '>' are pretty widely supported for this
 #	builtin. Unlike with [[ ]], we need to quote everything.
-elif PATH=/dev/null; eval "[ 'a${CCn}b' '<' 'a${CCn}bb' ] && [ 'a${CCn}bb' '>' 'a${CCn}b' ]"
+elif thisshellhas --bi=[ && eval "[ 'a${CCn}b' '<' 'a${CCn}bb' ] && [ 'a${CCn}bb' '>' 'a${CCn}b' ]"
 then
-	PATH=${_Msh_PATH}
 	sortsbefore() {
 		case $# in
 		( 2 )	[ "X$1" '<' "X$2" ] || { let "$? > 1" && die "sortsbefore: '[' failed"; } ;;
@@ -3181,7 +3168,7 @@ then
 	}
 
 # ...	Fall back to the POSIX way with 'expr'.
-elif PATH=${_Msh_PATH}; eval "command -p expr 'a${CCn}b' '<' 'a${CCn}bb' && ! command -p expr 'a${CCn}bb' '<' 'a${CCn}b'"
+elif eval "command -p expr 'a${CCn}b' '<' 'a${CCn}bb' && ! command -p expr 'a${CCn}bb' '<' 'a${CCn}b'"
 then
 	sortsbefore() {
 		case $# in
@@ -3196,9 +3183,8 @@ then
 		esac
 	}
 else
-	printf '%s\n' "Can't run modernish: no valid 'expr' command in default system path." 1>&3
-	[ -e "$HOME/.modernish-force" ] || exit 127
-	printf "Proceeding anwyay. 'sortsbefore' and 'sortsafter' won't work." 1>&3
+	_Msh_initExit "No valid 'expr' command in default system path." \
+		"'sortsbefore' and 'sortsafter' require this." 2>&3
 fi 3>&2 >/dev/null 2>&1
 
 # String comparison tests:
@@ -3244,6 +3230,9 @@ endswith() {
 #
 # Empty removal handling: if one argument is omitted, assume the first was a
 # removed unquoted empty parameter and return false. 0 arguments = fatal error.
+#
+# Note: conflicts with external 'match' command from the Mail Avenger package.
+# Use 'extern match' to use an external 'match' command.
 match() {
 	case ${#},${1-},${2-} in
 	( 2,"${1-}",*\\* )
@@ -3270,7 +3259,7 @@ match() {
 #
 # TODO:	Work around inconsistencies with (a) empty regex or (b) multi-line
 #	regex. Some shells' "[[" and "grep -E" act differently from each other.
-if ( PATH=/dev/null; eval "[[ xyz =~ ^[a-z]+$ ]]" ); then
+if thisshellhas --rw=[[ && ( eval "[[ xyz =~ ^[a-z]+$ ]]" ); then
 	# Wrap the function definition in 'eval', otherwise shells that
 	# have '[[' but don't support '=~' fail to parse the script.
 	eval 'ematch() {
@@ -3282,7 +3271,7 @@ if ( PATH=/dev/null; eval "[[ xyz =~ ^[a-z]+$ ]]" ); then
 	}'
 # ('eval' is needed by zsh below, otherwise it will exit main shell at this
 # point if its regex module is not found)
-elif eval "[ xyz '=~' '^[a-z]+\$' ]"; then
+elif thisshellhas --bi=[ && eval "[ xyz '=~' '^[a-z]+\$' ]"; then
 	# yash supports extended regex matching in builtin test/[.
 	ematch() {
 		case $# in
@@ -3291,16 +3280,31 @@ elif eval "[ xyz '=~' '^[a-z]+\$' ]"; then
 		( * )	_Msh_dieArgs ematch "$#" '2 or 1' ;;
 		esac
 	}
-else
-	# default/POSIX: use grep (this is some 30-60 times slower).
-	ematch() {
-		case $# in
-		( 2 )	printf '%s\n' "$1" | command -p grep -qE "$2" || { let "$? > 1" && die "ematch: 'grep' failed"; } ;;
+elif thisshellhas HERESTR; then
+	# Use grep with a here-string. Here-strings are significantly faster than here-documents on mksh.
+	_Msh_ematch_grep=$(command -pv grep || command -v grep) || _Msh_initExit 3 "can't locate grep" 2>&3 || return
+	eval "ematch() {
+		case \$# in
+		( 2 )	${_Msh_ematch_grep} -qE \"\$2\" <<<\"\$1\" || { let \"\$? > 1\" && die \"ematch: 'grep' failed\"; } ;;
 		( 1 )	return 1 ;;
-		( * )	_Msh_dieArgs ematch "$#" '2 or 1' ;;
+		( * )	_Msh_dieArgs ematch \"\$#\" '2 or 1' ;;
 		esac
-	}
-fi 2>/dev/null
+	}"
+	unset -v _Msh_ematch_grep
+else
+	# Default/POSIX: use grep with here-document. IMPORTANT: preserve leading tabs!!!
+	_Msh_ematch_grep=$(command -pv grep || command -v grep) || _Msh_initExit 3 "can't locate grep" 2>&3 || return
+	eval "ematch() {
+		case \$# in
+		( 2 )	${_Msh_ematch_grep} -qE \"\$2\" <<-EOF || { let \"\$? > 1\" && die \"ematch: 'grep' failed\"; } ;;
+			\$1
+			EOF
+		( 1 )	return 1 ;;
+		( * )	_Msh_dieArgs ematch \"\$#\" '2 or 1' ;;
+		esac
+	}"
+	unset -v _Msh_ematch_grep
+fi 3>&2 2>/dev/null
 
 # --- General file tests. ---
 # The can() and is() functions deal correctly with empty removal so are good
@@ -3312,11 +3316,11 @@ fi 2>/dev/null
 #		Test if this program can read from or write to a file or
 #		directory. Work around botched '['/'[[' logic that claims
 #		you can (-r)ead from or (-w)rite to a directory even if its
-#		"x" bit is not set.
+#		"x" bit is not set. (-d && ( -[rw] && -x ) || -[rw])
 #	can exec
-#		Test if non-directory file is executable. (-x)
+#		Test if non-directory file is executable. (-x && ! -d)
 #	can traverse:
-#		Test if you can traverse through a directory. (-x)
+#		Test if you can traverse through a directory. (-x && -d)
 #		Distinct from 'can exec' to help avoid bugs.
 # is():
 #	--- ownership tests ---
@@ -3346,7 +3350,26 @@ fi 2>/dev/null
 #		Test if file exists (even if it's an invalid symlink).
 #	is -L present:
 #		Test if file exists and is not an invalid symlink.
-#	--- comparison tests ---
+#	--- content test ---
+#	is nonempty:
+#		Test if file exists, is not an invalid symlink, and is non-empty. Unlike 'test -s',
+#		this also works for directories in which you have read permission (both r and x
+#		bits set). A race condition with tests like this is inevitable (even with the
+#		traditional 'test -s'). Be careful with parallel processing!
+#		Exit status:
+#		0: file or directory (after resolving any symlinks) is not empty
+#		1: file or directory is empty, doesn't exist, or is an invalid symlink
+#		2: no read permission in directory, so cannot test if directory is empty
+#		The directory testing method was kindly provided by Stéphane Chazelas in:
+#		Message-ID: <20150524190928.GB6744@chaz.gmail.com>
+#		https://groups.google.com/forum/#!original/comp.unix.shell/M_gDU9uk8Rk/FyiS9m-RFYAJ
+#		BUG: reads entire directory; slow/expensive for very large directories.
+#	--- file descriptor test ---
+#	is onterminal:
+#		Test if file descriptor is open and associated with a terminal.
+#		(Note: POSIX specifies that file descriptors can be 0 to minimum 19,
+#		but most shells only support file descriptors between 0 and 9.)
+#	--- comparison tests (2 arguments) ---
 #	is newer, is older, is samefile:
 #		Test if file 1 is newer than, older than, or (through hard
 #		links or symlinks) the same file as file 2. (Note: the -nt,
@@ -3489,7 +3512,7 @@ else
 			( traverse )
 				[ -x "$2" ] && [ -d "$2" ] ;;
 			( * )	die "can: invalid operator: $1" || return ;;
-			esac || { let "$? > 1" && die "can: '[' failed"; } ;;
+			esac || { let "$? > 1" && die "can $1: '[' failed"; } ;;
 		( * )	_Msh_dieArgs can "$#" '1 or 2' ;;
 		esac
 	}
@@ -3606,18 +3629,20 @@ else
 	fi
 fi
 
+# For thisshellhas(): Now that we have is(), we can replace the preliminary
+# _Msh_doCapTest() with a more straightforward and robust one.
+_Msh_doCapTest() {
+	is -L reg "$MSH_PREFIX/libexec/modernish/cap/$1.t" &&
+		. "$MSH_PREFIX/libexec/modernish/cap/$1.t"
+}
+
+
 # -------------------
 
 # Initialization, phase 2.
 
 unset -v _Msh_PATH
-
-# Now that we have is(), we can replace the preliminary _Msh_doCapTest with
-# a slightly more robust one.
-_Msh_doCapTest() {
-	is -L reg "$MSH_PREFIX/libexec/modernish/cap/$1.t" &&
-		. "$MSH_PREFIX/libexec/modernish/cap/$1.t"
-}
+unset -f _Msh_initExit
 
 # If shell supports it, then set modernish functions to read-only.
 if thisshellhas ROFUNC; then
