bugfix: 'clearstack --trap=DIE' tried to unset nonexistent shell-native trap

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -2907,8 +2907,11 @@ clearstack() {
 			pop _Msh_cS_key _Msh_cS_f
 			_Msh_cS_V=_Msh_trap${_Msh_sigv}
 			if stackempty --force "_Msh_trap${_Msh_sigv}_opt" && ! isset "_Msh_POSIXtrap${_Msh_sigv}"; then
-				identic "${_Msh_sig}" EXIT && _Msh_sig=0  # BUG_TRAPEXIT compat
-				command trap - "${_Msh_sig}"
+				case ${_Msh_sig} in
+				(EXIT)	command trap - 0 ;;	# BUG_TRAPEXIT COMPAT
+				(DIE)	;;
+				( * )	command trap - "${_Msh_sig}" ;;
+				esac || die "clearstack: internal error" || return
 			fi
 			unset -v _Msh_sig _Msh_sigv ;;
 		( -o )	_Msh_o=y	# expect another argument
