_Msh_POSIXtrap(): stuff for v=$(trap): avoid spurious internal error
bin/modernish:
- The fix in commit 25b39a2e was incomplete. Apply the same fix
  for the code supporting variable=$(trap) on all shells.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -2900,11 +2900,11 @@ _Msh_POSIXtrap() {
 				_Msh_sigs2cleanup=${_Msh_sigs2cleanup}\ ${_Msh_sig}
 			done
 			# With the dummy traps corresponding to our trap variables now set in this subshell, try again.
-			if thisshellhas BUG_UPP; then
-				command trap ${1+"$@"}
-			else
-				command trap "$@"
-			fi >> "${_Msh_trapd}/systraps" || die "trap: internal error: can't write to temp file" || return
+			{	case $# in
+				( 0 )	command trap ;;		# BUG_UPP compat
+				( * )	command trap "$@" ;;
+				esac || die "trap: internal error: system 'trap' command failed, though validated" || return
+			} >> "${_Msh_trapd}/systraps" || die "trap: internal error: can't write to temp file" || return
 			# Unset the dummy traps.
 			eval "command trap - ${_Msh_sigs2cleanup}"
 			unset -v _Msh_sigs2cleanup _Msh_sig _Msh_signum
