v0.17.9-dev: use(): add -l option to list loaded modules
The new option lists the loaded modules in the order in which they
were loaded.

bin/modernish: use():
- Add -l option.
- On interactive shells, confirm loading a module directory too.
- Refactor to make this work sensibly. The _Msh_using internal
  variable is now newline-separated. The code for recursively
  loading a module directory is moved to _Msh_doUse() where it can
  safely overwrite the positional parameters.
- When loading recursively, use '--' in case a name starts with -.
- Version bump.

README.md:
- Add use -l documentation.
- Copy-edit.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -127,7 +127,7 @@ _Msh_initExit() {
 }
 
 # The version and location of modernish.
-MSH_VERSION=0.17.8-dev
+MSH_VERSION=0.17.9-dev
 MSH_PREFIX=${srcdir:-$(_Msh_D=.; case $0 in (*/bin/modernish) _Msh_D=${0%/bin/*};; esac; cd "$_Msh_D" && pwd)} || _Msh_initExit # this line will be changed by install.sh
 MSH_MDL=$MSH_PREFIX/lib/modernish/mdl
 MSH_AUX=$MSH_PREFIX/lib/modernish/aux
@@ -541,19 +541,20 @@ setstatus() {
 
 # Use a modernish module.
 # If the module is already loaded, does nothing and exits successfully
-# (status 0), preventing dependency loops. The space-separated global
+# (status 0), preventing dependency loops. The newline-separated global
 # internal variable _Msh_using keeps track of the modules in use.
 # If a directory D is given and no module file D.mm is found, then
 # 'use' will recursively load the modules in that directory.
 # Option -q: query if the module is already loaded.
 # Option -e: query if the module exists.
+# Option -l: list modules in use.
 _Msh_using=''
 use() {
 	unset -v _Msh_use_o
 	while	case ${1-} in
 		( -- )		shift; break ;;
-		( -q )		_Msh_use_o=q ;;
-		( -e )		_Msh_use_o=e ;;
+		( -[qel] )	isset _Msh_use_o && die "use: options cannot be combined"
+				_Msh_use_o=${1#-} ;;
 		( -* )		die "use: unknown option: $1" ;;
 		( * )		break ;;
 		esac
@@ -561,6 +562,10 @@ use() {
 		shift
 	done
 	case ${_Msh_use_o-} in
+	( l )	let "$#" && die "use -l: excess arguments"
+		str empty "${_Msh_using}" || putln "${_Msh_using}"
+		unset -v _Msh_use_o
+		return 0 ;;
 	( ? )	let "$# == 1" || die "use -${_Msh_use_o}: need 1 argument, got $#" ;;
 	( * )	let "$#" || die "use: need at least 1 argument, got $#" ;;
 	esac
@@ -568,7 +573,11 @@ use() {
 	( '' | *[!$SHELLSAFECHARS]* | /* | */ | *//* | *.mm )
 		die "use: invalid module name: $1" ;;
 	esac
-	str in " ${_Msh_using} " " $1 " && unset -v _Msh_use_o && return 0
+	case $CCn${_Msh_using}$CCn in
+	( *"$CCn$1$CCn"* ) # module already loaded
+		unset -v _Msh_use_o
+		return 0 ;;
+	esac
 	case ${_Msh_use_o-} in
 	( q )	unset -v _Msh_use_o
 		return 1 ;;
@@ -576,8 +585,17 @@ use() {
 		is reg "$MSH_MDL/$1.mm" || is dir "$MSH_MDL/$1"
 		return ;;
 	esac
-	_Msh_using=${_Msh_using}${_Msh_using:+ }$1
-	if is dir "$MSH_MDL/$1" && ! is reg "$MSH_MDL/$1.mm"; then
+	_Msh_doUse "$@"
+	case $? in
+	( 0 )	if isset -i; then putln "Using $1" >&2; fi
+		_Msh_using=${_Msh_using}${_Msh_using:+$CCn}$1 ;;
+	( * )	die "use: initialisation of module $1 failed" ;;
+	esac
+}
+_Msh_doUse() {
+	if is reg "$MSH_MDL/$1.mm"; then
+		. "$MSH_MDL/$1.mm" >&2
+	elif is dir "$MSH_MDL/$1"; then
 		let "$# == 1" || die "use: arguments cannot be passed to module directory: $1"
 		# recursively initialise all modules...
 		push -f; set +f; set -- "$MSH_MDL/$1"/*; pop -f
@@ -586,22 +604,12 @@ use() {
 			_Msh_use_F=${_Msh_use_F#"$MSH_MDL/"}	# "
 			_Msh_use_F=${_Msh_use_F%.mm}
 			str match "${_Msh_use_F}" "*[!$SHELLSAFECHARS]*" && continue
-			use "${_Msh_use_F}"
+			use -- "${_Msh_use_F}"
 		done
 		unset -v _Msh_use_F
-		return
+	else
+		die "use: module $1 not found"
 	fi
-	is reg "$MSH_MDL/$1.mm" || die "use: module $1 not found"
-	_Msh_doUse "$@"
-	case $? in
-	( 0 )	if isset -i; then putln "Using $1"; fi ;;
-	( * )	die "use: initialisation of module $1 failed" ;;
-	esac
-} >&2
-# Wrapping the dot command in its own function works around bugs or quirks
-# with 'return' on a couple of shells (yash < 2.44, older FreeBSD sh).
-_Msh_doUse() {
-	. "$MSH_MDL/$1.mm"
 }
 
 
