put/putln: bugfix: accept $? > 1 for I/O error (re: 7610610a)
FreeBSD sh returns status 2 for I/O error instead of status 1.
As of 7610610a, this was killing modernish on FreeBSD sh upon
trying to test for BUG_PUTIOERR.

bin/modernish: put()/putln():
- Accept any status <= 125 (with 126 meaning the utility couldn't
  be executed, 127 that it was not found, and > 128 a signal).
- For the versions using the ksh/zsh 'print' builtin, accept
  $SIGPIPESTATUS like the rest, just in case.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -1937,7 +1937,7 @@ if thisshellhas print LOCALVARS; then
 		( 0 )	command print ;;
 		( 1 )	command print -r -- "$1" ;;
 		( * )	local IFS="$CCn" && command print -r -- "$*" ;;
-		esac || { let "$? > 1" && die "putln: internal error"; }
+		esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "putln: internal error"; }
 	}
 
 	put() {
@@ -1945,17 +1945,15 @@ if thisshellhas print LOCALVARS; then
 		( [01], ) ;;
 		( 1,n )  command print -nr -- "$1" ;;
 		( * )	 local IFS=" " && command print -nr -- "$*" ;;
-		esac || { let "$? > 1" && die "put: internal error"; }
+		esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "put: internal error"; }
 	}'
-
 else
 	# For most shells, use 'printf' for putln and put.
-	# 'printf' could be an external command, so tolerate SIGPIPE.
 	putln() {
 		case $# in
 		( 0 )	PATH=$DEFPATH command printf '\n' ;;
 		( * )	PATH=$DEFPATH command printf '%s\n' "$@" ;;
-		esac || { let "$? > 1 && $? != SIGPIPESTATUS" && die "putln: internal error"; }
+		esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "putln: internal error"; }
 	}
 
 	if thisshellhas LOCALVARS; then
@@ -1964,7 +1962,7 @@ else
 			( [01], ) ;;
 			( 1,n )  PATH=$DEFPATH command printf "%s" "$1" ;;
 			( * )	 local IFS=" " && PATH=$DEFPATH command printf "%s" "$*" ;;
-			esac || { let "$? > 1 && $? != SIGPIPESTATUS" && die "put: internal error"; }
+			esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "put: internal error"; }
 		}'
 	elif thisshellhas KSH93FUNC; then
 		eval 'function put {
@@ -1972,7 +1970,7 @@ else
 			( [01], ) ;;
 			( 1,n )  PATH=$DEFPATH command printf "%s" "$1" ;;
 			( * )	 typeset IFS=" " && PATH=$DEFPATH command printf "%s" "$*" ;;
-			esac || { let "$? > 1 && $? != SIGPIPESTATUS" && die "put: internal error"; }
+			esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "put: internal error"; }
 		}'
 	else
 		# default (POSIX, no local variables)
@@ -1983,7 +1981,7 @@ else
 			( * )	 push IFS; IFS=' '
 				 PATH=$DEFPATH command printf '%s' "$*"
 				 pop --keepstatus IFS ;;
-			esac || { let "$? > 1 && $? != SIGPIPESTATUS" && die "put: internal error"; }
+			esac || { let "$? > 125 && $? != SIGPIPESTATUS" && die "put: internal error"; }
 		}
 	fi
 fi
