tests/run.sh: preload modules; use loop/with
bin/modernish:
- Allow tests/run.sh to use modules depending on aliases even on
  ksh93 by pre-loading the modules from hashbang commands as with
  portable modernish programs.
- Fix a bug in the temp function that does the preloading: the
  variable containing the use command wasn't quoted properly after
  restoring split/glob settings.
- Replace a couple of unneeded 'command exit' by simple 'exit'.

libexec/modernish/tests/run.sh:
- Use hashbang commands to load modules.
- Since we're already loading loop/with, might as well use it here
  too. (This properly redoes 38a8f91c1fc902811bc98fbe75d2af629af583ab.)

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -5153,7 +5153,7 @@ _Msh_tmp_doHashbangPreload() {
 			esac
 		done
 		pop IFS -f
-		eval ${_Msh_doHbPl_C} || die "hashbang command failed: ${_Msh_doHbPl_L}"
+		eval "${_Msh_doHbPl_C}" || die "hashbang command failed: ${_Msh_doHbPl_L}"
 	done
 	unset -v _Msh_doHbPl_L _Msh_doHbPl_C _Msh_doHbPl_a
 }
@@ -5307,12 +5307,14 @@ if let "$#"; then
 			unset -f _Msh_tmp_doUse ;;
 		( --version )
 			putln "$MSH_VERSION"
-			command exit
+			exit
 			;;
 		( --test )
 			shift
+			_Msh_tmp_doHashbangPreload < "$MSH_PREFIX/libexec/modernish/tests/run.sh" || exit
+			unset -f _Msh_tmp_doHashbangPreload
 			. "$MSH_PREFIX/libexec/modernish/tests/run.sh"
-			command exit
+			exit
 			;;
 		( -- )
 			shift
