trap stack: clear out SIGINT (die()) traps on interactive shells
bin/modernish:
- Always clear out SIGINT traps on interactive shells after first
  execution. Since SIGINT is used for cleanup and command
  interruption by die() on interactive shells, not clearing them
  out was causing hairy side effects that were impossible to handle
  properly.
- Refactor _Msh_doTraps() to make its logic more straightforward
  and easier to understand.

README.md:
- Document the new SIGINT behaviour on interactive shells.
- Move a couple of other related things to more sensible places.

diff --git a/bin/modernish b/bin/modernish
--- a/bin/modernish
+++ b/bin/modernish
@@ -3213,33 +3213,34 @@ _Msh_doTraps() {
 	# their own traps to clean up after themselves.
 	if isset "_Msh_POSIXtrap${2}"; then
 		_Msh_doPosixTrap "${2}"
-	elif case $1 in (CONT|EXIT|ERR|DEBUG|KEYBD) ! : ;; esac && ! insubshell; then
-		# If there is no emulated POSIX trap, and the signal is not
-		# CONT or a pseudosignal, and we're not in a subshell, the
-		# signal was ignored contrary to expectations. So unignore and resend it,
-		# with special handling for SIGINT (Ctrl+C) on an interactive shell.
-		if isset -i; then
-			if identic "$1" INT; then
-				clearstack --force --trap=INT	# since there is no POSIX trap, this also unsets the native trap
-				if isset BASH_VERSION; then
-					# Handle Bash specially for SIGINT on an interactive shell. Bash (at least
-					# up to 4.4) has a bug that makes the interactive shell exit upon resending
-					# SIGINT, as below. However, it also has a quirk: SIGINT is not ignored on
-					# interactive shells if the native shell trap is non-empty (which it is, if
-					# you set any trap using modernish). So the workaround is to do nothing.
-					return
-				fi
-				command kill -s INT "$$"
-				return
-			fi
-		else
-			# bash and ksh will trigger the EXIT trap on sending any untrapped signal, which is
-			# inconsistent with other shells. Remedy this for stack traps in scripts only.
+	fi
+	# On interactive shells, SIGINT is used for cleanup after die(), so clear
+	# out the SIGINT stack traps to make sure they are executed only once.
+	if isset -i && identic "$1" INT; then
+		clearstack --force --trap=INT
+		unset -v "_Msh_POSIXtrap${2}"
+	fi
+	# If there is no emulated POSIX trap, and the signal is not CONT or a pseudosignal, and we're
+	# not in a subshell, the signal was ignored contrary to expectations. So unignore and resend it.
+	if ! isset "_Msh_POSIXtrap${2}" && case $1 in (CONT|EXIT|ERR|DEBUG|KEYBD) ! : ;; esac && ! insubshell; then
+		# bash and ksh will trigger the EXIT trap on sending any untrapped signal, which is
+		# inconsistent with other shells. Remedy this for stack traps in scripts only.
+		if ! isset -i; then
 			command trap - EXIT
 		fi
 		# Unignore (by unsetting the trap) and resend the signal, possibly killing the shell.
 		command trap - "$1"
 		case $1 in
+		( INT )	# Handle Bash specially for SIGINT on an interactive shell. Bash (at least
+			# up to 4.4) has a bug that makes the interactive shell exit upon resending
+			# SIGINT, as below. However, it also has a quirk: SIGINT is not ignored on
+			# interactive shells if the native shell trap is non-empty (which it is, if
+			# you set any trap using modernish). So the workaround is to do nothing.
+			if isset BASH_VERSION && isset -i; then
+				return
+			else
+				command kill -s INT "$$"
+			fi ;;
 		( *[!0123456789]* )
 			command kill -s "$1" "$$" ;;	# signal name
 		( * )	command kill "-$1" "$$" ;;	# signal with no name (number only)
