Introduce stack --key option to help avoid stack corruption
bin/modernish:
- push(), pop(): Add `--key=` option, an advanced feature that can
  help different modules or funtions to use the same variable stack
  safely. If a key is given to `push`, then for each *item*, the
  given key *value* is stored along with the variable's value for
  that position in the stack. Subsequently, restoring that value
  with `pop` will only succeed if the key option with the same key
  value is given to the `pop` invocation. Similarly, popping a
  keyless value only succeeds if no key is given to `pop`. If there
  is any key mismatch, no changes are made and pop returns status
  2. Note that this is a robustness/convenience feature, not a
  security feature; the keys are not hidden in any way.
- stackempty(): Report stack empty if there is a key mismatch,
  not just if the stack is really empty, except if --force is
  given. The real meaning is "can we pop something?".
- clearstack(): By default, clear entries until a key mismatch is
  encountered. Use --force to always clear the whole stack.
- pushtrap(), poptrap(): Add --key= option that uses the new
  functionality inherited from push() and pop(). Not sure if
  it will actually be needed here, but for completeness' sake...

README.md:
- Document all the above changes.

libexec/modernish/var/setlocal.mm:
- Use the new --key feature for push and pop: an internal key
  '_Msh_setlocal' keeps the main program from accidentally popping
  global variables off the stack, preventing stack corruption.
  This should make var/setlocal considerably more robust.

share/doc/modernish/examples/setlocal-test:
- Add a test for the above-mentioned stack corruption protection.

libexec/modernish/tests/setlocal.t
- Added. New test suite for var/setlocal testing the new
  protections against stack corruption provided by the new stack
  key feature. Based in part on examples/setlocal-test, but not
  everything can be used as the last test deliberately kills the
  script. Therefore keep both.

libexec/modernish/tests/run.sh:
- Use var/setlocal for the new setlocal.t.

diff --git a/share/doc/modernish/examples/setlocal-test b/share/doc/modernish/examples/setlocal-test
--- a/share/doc/modernish/examples/setlocal-test
+++ b/share/doc/modernish/examples/setlocal-test
@@ -60,7 +60,7 @@ if thisshellhas BUG_FNSUBSH; then
 else
 	putln '(If you see anything other than the files in your PWD below, there is an undiscovered bug!)'
 fi
-# (Due to a bug, mksh throws a syntax error if you use $( ) instead of ` `.
+# (Due to a bug, mksh [up to R54 2016/11/11] throws a syntax error if you use $( ) instead of ` `.
 # Not that this really matters. In real-world programs you would not need to do this.)
 result=`{ setlocal --nosplit --doglob; printf '[%s] ' * | fold -s; endlocal }`
 putln $result
@@ -70,9 +70,28 @@ putln $result
 putln '' '------Test 3a------'
 putln one two three four | { setlocal X --split=$CCn; while read X; do put "[$X] "; done; echo; endlocal }
 
-putln '' '------Test 4------' 'This test should fail with: "stack corrupted (failed to pop globals)".'
+putln '' '------Test 4------' 'Testing protection against stack corruption.'
+{ setlocal testvar='stack corruption protection test: '
+	put $testvar
+	push var3
+	push var3 var2
+	push var3 var2 var1
+	pop var3 var2 testvar var1   # this should fail due to a key mismatch
+	let "$? == 2" || return 1
+	stacksize -s var3
+	let "REPLY == 3" || return 1
+	stacksize -s var2
+	let "REPLY == 2" || return 1
+	stacksize -s var1
+	let "REPLY == 1" || return 1
+	clearstack var1 var2 var3
+endlocal } && putln "ok" || putln "FAILED"
+
+putln '' '------Test 5------' 'This test should fail with: "stack corrupted (failed to pop globals)".'
 { setlocal testvar=$CCv'stack corruption test test...'$CCn
 	putln $testvar
-	pop testvar
+	push testvar
+	# Failing to restore a local variable's stack within the block will stop 'setlocal'
+	# from restoring global settings due to a key mismatch, killing the program.
 endlocal }
 putln 'Bad! We should never get here.'
