Add support for Android/Termux
Android seems to go out of its way to break POSIX compliance and
even basic Unix/Linux assumptions: you cannot read /dev or even /,
there is no /tmp, there is no 'getconf PATH' (even if getconf(1) is
installed, which by default it isn't).

Also, signals are weird; signals 32 through 40 exist but have no
names. Again, not a compliant situation. On bash, this caused an
internal error for trap 38; the trap command on bash outputs it as
ignored, using the number since there is no name, and modernish was
trying to process that as a signal name.

This commit adds code to cope with all that. It was tested on
Android 14.0 with Termux 0.118.0 on the Android emulator provided
by Android Studio on macOS.

lib/modernish/mdl/_IN/sig.mm:
- init: Keep track of the number of signals.
- init: Stop trying as soon as 'trap - signumber' throws an error.
  This assumes the available signal numbers are contiguous, which
  AFAIK is true everywhere even if some lack names (knock on wood).
- _Msh_arg2sig(): Add support for signal numbers as names: don't
  return an error status for a signal number if it is within the
  range of the number of signals. This fixes the internal error.

lib/modernish/mdl/sys/base/mktemp.mm,
lib/modernish/mdl/var/stack/trap.mm:
- Cope with the absence of /tmp. Require XDG_RUNTIME_DIR or TMPDIR.

lib/modernish/adj/defpath.sh:
- Add support for Termux (/data/data/com.termux/files/usr/bin).
  Since its getconf(1) doesn't know 'PATH', hardcode it.

lib/modernish/cap/BUG_IFSGLOBP.t,
lib/modernish/cap/QRK_GLOBDOTS.t,
lib/modernish/tst/io.t,
lib/modernish/tst/local.t,
lib/modernish/tst/loop_cond.t:
- Avoid reading /, /dev or /tmp.

lib/modernish/tst/run.sh:
- Tolerate SIGPIPE in printf failure (with the -P option to
  harden()); this is needed on mksh where printf is not a built-in.
- Do not use /tmp when making the temp directory.

install.sh:
- Add support for installing in /data/data/com.termux/files/usr by
  default -- this is writable for the single user of the system.

Thanks to @tabbyrobin for the request.
Resolves: https://github.com/modernish/modernish/issues/23

diff --git a/lib/_install/lib/modernish/mdl/var/stack/trap.mm.bundle.diff b/lib/_install/lib/modernish/mdl/var/stack/trap.mm.bundle.diff
--- a/lib/_install/lib/modernish/mdl/var/stack/trap.mm.bundle.diff
+++ b/lib/_install/lib/modernish/mdl/var/stack/trap.mm.bundle.diff
@@ -1,5 +1,5 @@
---- lib/modernish/mdl/var/stack/trap.mm	2023-09-22 18:19:20.000000000 +0100
-+++ lib/modernish/mdl/var/stack/trap.mm	2023-09-22 18:32:28.000000000 +0100
+--- lib/modernish/mdl/var/stack/trap.mm	2024-03-22 18:27:44.000000000 +0000
++++ lib/modernish/mdl/var/stack/trap.mm	2024-03-22 18:30:52.000000000 +0000
 @@ -34,7 +34,6 @@
  use _IN/sig	# provides _Msh_arg2sig()
  use var/shellquote
@@ -8,10 +8,10 @@
  
  # -----------------
  
-@@ -169,11 +168,6 @@
- _Msh_doTraps() {
+@@ -170,11 +169,6 @@
  	# Save current exit status in $3.
- 	set -- "$1" "$2" "$?"
+ 	set -- "${1-}" "${2-}" "$?" "${3-}"
+ 	str eq "$4" "${_Msh_trap_Salt}" || die "trap: internal error: bad salt"
 -	# Handle INT (DIE) traps on interactive shells specially.
 -	if isset -i && str eq "$1" INT && ! insubshell; then
 -		_Msh_doINTtrap "$2" "$3"
@@ -20,7 +20,7 @@
  	# Avoid CHLD subshell trap actions triggering SIGCHLD themselves => infinite recursion.
  	case $1 in
  	( CHLD ) command trap : CHLD ;;
-@@ -226,9 +220,7 @@
+@@ -227,9 +221,7 @@
  	esac
  	# bash and *ksh trigger the EXIT trap when an untrapped signal terminates the shell, which is
  	# inconsistent with other shells. Remedy this for stack traps on non-interactive shells only.
@@ -31,7 +31,7 @@
  	# Unset the trap and resend the signal, possibly killing the shell.
  	command trap - "$1"
  	case $1 in
-@@ -241,45 +233,10 @@
+@@ -242,45 +234,10 @@
  	thisshellhas BUG_TRAPUNSRE && return "$3"
  	# Still here: restore the trap.
  	_Msh_setSysTrap "$1" "$2"
@@ -78,7 +78,7 @@
  
  # Wrapper function for a stacked trap action. Always run this in a subshell.
  _Msh_fork=''
-@@ -363,11 +320,7 @@
+@@ -364,11 +321,7 @@
  			&& . "${_Msh_trapd}/systraps" \
  			&& command alias trap='_Msh_POSIXtrap' || die "trap: internal error"
  			# Cleanup.
